name: LEGO-Pyomo_env
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.10.1
  - openpyxl=3.1.2
  - pandas=2.2.2
  - pip=24.0
  - psutil=6.1.0
  - pyomo=6.9.2
  - python=3.12.2
  - rich=13.7.1
  - rich-argparse=1.6.0
  - tabulate=0.9.0
  - pip:
      - pulp==2.9.0
