name: Simplified-Technical-Representation_env
channels:
  - defaults
  - conda-forge
dependencies:
  - openpyxl=3.1.2
  - pandas=2.2.2
  - pip=24.0
  - pyomo=6.8.0
  - python=3.12.2
  - rich=13.7.1
  - tabulate=0.9.0
