name: LEGO-Pyomo_env
channels:
  - defaults
  - conda-forge
dependencies:
  - ibmdecisionoptimization::cplex=22.1.2  # Currently doesn't work for MacOS - re-activate GitHub tests when fixed (GitHub issue #30)
  - highspy=1.11.0
  - matplotlib=3.10.3
  - openmpi=4.1.3
  - openpyxl=3.1.5
  - pandas=2.2.3
  - pandas-stubs=2.3.0.250703
  - pip=25.1
  - psutil=7.0.0
  - py7zr=1.0.0
  - pyomo=6.9.2
  - pytest=8.4.0
  - python=3.12.11
  - python-calamine=0.5.3
  - rich=14.0.0
  - rich-argparse=1.7.0
  - tabulate=0.9.0
  - tsam=2.3.9
  - pip:
      - gurobipy==12.0.3
      - mpi4py==4.0.3
      - mpi-sppy==0.12.1  # https://doi.org/10.1007/s12532-023-00247-3
      - pulp==3.1.1
      - -e InOutModule  # Editable install for InOutModule (submodule of this repository)
