"""Run an MK experiment grid on a Slurm cluster, one job per solve (see README.md, section "Cluster runs").

    python research/MK/cluster.py submit   research/MK/experiments/experiment.toml [--dry-run]
    python research/MK/cluster.py status   experiment [--list STATE] [--filter PATTERN]
    python research/MK/cluster.py restart  experiment [PATTERN ...] [--failed] [--mem 200G | --mem-factor 1.5] [--cpus N] [--time T]
    python research/MK/cluster.py prioritize experiment [--nice-step N]
    python research/MK/cluster.py log      experiment KEY
    python research/MK/cluster.py cancel   experiment

Run from the repo root on the login node. Standard library only (Python >= 3.11 for tomllib).
"""
import argparse
import datetime
import fnmatch
import itertools
import json
import os
import re
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    sys.exit("cluster.py needs Python >= 3.11 (tomllib)")

HERE = Path(__file__).resolve().parent
RUNS_DIR = HERE / "runs"
DEFAULT_NICE_STEP = 100  # [slurm] nice_step: sbatch --nice per rank (MUSICA age weight 10000 per 14 days = ~30 per hour)

# Grid tasks in dependency order (a task only depends on tasks listed before it)
GRID_TASKS = ["main", "operational", "regret", "invest-regret", "operational-regret", "original-invest-regret", "original-regret"]
TRUTH_TASKS = {"main", "operational", "original-invest-regret"}  # tasks that also exist for the Truth edge handling
ORIGINAL_TASKS = {"original-invest-regret", "original-regret"}  # only for the unshifted transition matrix
TASK_DEPS = {  # (task, edge) -> [(task, edge)] within the same grid point; "EDGE" = the task's own edge
    "main": [],
    "operational": [("main", "Truth")],
    "regret": [("main", "EDGE")],
    "invest-regret": [("main", "EDGE")],
    "operational-regret": [("main", "Truth"), ("operational", "EDGE")],
    "original-invest-regret": [("main", "EDGE")],
    "original-regret": [("main", "EDGE")],
}

# Job names: squeue shows only the first 8 characters, so every job name starts with an 8-character code
# <dataset 2><task 4><edge 2> (e.g. 'TXmainMk', 'NRoRgrTr'), followed by '_' and the full group name
TASK_CODES = {"main": "main", "operational": "oper", "regret": "rgrt", "invest-regret": "iRgr", "operational-regret": "oRgr",
              "original-invest-regret": "OiRg", "original-regret": "ORgr", "prepare": "prep", "truth-original": "trOr"}
EDGE_CODES = {"Truth": "Tr", "NoEnf": "NE", "Cyclic": "Cy", "Markov": "Mk", None: "--"}

# Slurm state -> category shown by `status`
DONE, RUNNING, PENDING, BLOCKED, FAILED, UNKNOWN = "done", "running", "pending", "blocked", "failed", "unknown"
CATEGORIES = [DONE, RUNNING, PENDING, BLOCKED, FAILED, UNKNOWN]
_FAILED_STATES = {"FAILED", "OUT_OF_MEMORY", "TIMEOUT", "CANCELLED", "NODE_FAIL", "PREEMPTED", "BOOT_FAIL", "DEADLINE"}
_RUNNING_STATES = {"RUNNING", "COMPLETING", "CONFIGURING", "SUSPENDED", "REQUEUED", "RESIZING"}

# Inserted into SBATCH_TEMPLATE for [markov] node_file_start_fraction: NodefileStart (GB) = fraction x granted memory
NODE_FILE_START_TEMPLATE = """NODE_FILE_START=$(awk -v m="${{SLURM_MEM_PER_NODE:?--mem not set}}" 'BEGIN {{printf "%.1f", m / 1024 * {fraction}}}')
CMD="${{CMD//@NODEFILESTART@/$NODE_FILE_START}}"
"""

SBATCH_TEMPLATE = """#!/bin/bash
#ASC --vanilla
#SBATCH -A {account}
#SBATCH -p {partition}
#SBATCH --qos={qos}
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --threads-per-core=1
{mail}# Generated by research/MK/cluster.py - runs task $TASK_INDEX (restart) or $SLURM_ARRAY_TASK_ID (array) of the command file $1.
set -eo pipefail

IDX="${{TASK_INDEX:-$SLURM_ARRAY_TASK_ID}}"
KEY=$(awk -F'\\t' -v i="$IDX" '$1 == i {{print $2; exit}}' "$1")
CMD=$(awk -F'\\t' -v i="$IDX" '$1 == i {{print $3; exit}}' "$1")
[ -n "$CMD" ] || {{ echo "No task $IDX in $1"; exit 1; }}

# Gurobi threads = allocated cores (Gurobi's default would use every CPU of the node); node files to node-local scratch
NODE_DIR="${{TMPDIR:-/tmp}}/gurobi-nodes-${{SLURM_JOB_ID}}"
trap 'rm -rf "$NODE_DIR"' EXIT
CMD="${{CMD//@THREADS@/$SLURM_CPUS_PER_TASK}}"
CMD="${{CMD//@NODEDIR@/$NODE_DIR}}"
{node_file_start}
echo "=========================================================="
echo "Task: $KEY"
echo "Slurm job: $SLURM_JOB_ID (array $SLURM_ARRAY_JOB_ID, index $IDX) on $SLURM_JOB_NODELIST"
echo "Cores: $SLURM_CPUS_PER_TASK, memory: $SLURM_MEM_PER_NODE MB"
echo "Command: $CMD"
echo "=========================================================="

{setup}

cd "{repo}"
# srun does not inherit --cpus-per-task from sbatch (Slurm >= 22.05); without this the solve runs on one core
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"
read -ra ARGS <<< "$CMD"
srun "${{ARGS[@]}}"
"""


########################################################################################################################
# Plan: config -> tasks
########################################################################################################################

def _tm_variant(spec: str) -> tuple[str, list[str]]:
    """'base' | 'shift:N' | 'perturb:R' -> (label used in task keys, Markov.py arguments)."""
    if spec == "base":
        return "base", []
    kind, _, value = spec.partition(":")
    if kind == "shift":
        return f"shiftTM{int(value)}", ["--shift-tm", str(int(value))]
    if kind == "perturb":
        return f"perturbTM{float(value):g}", ["--perturb-tm", value]
    raise ValueError(f"Unknown tm variant '{spec}' (use 'base', 'shift:N' or 'perturb:R')")


def _tm_entry(entry) -> tuple[str, list[str], set[float] | None, bool]:
    """grid.tm entry: 'spec' or {spec, stretch_demand = [...] (only these demand levels), low_priority = bool}
    -> (label, Markov.py arguments, allowed stretch_demand values or None = all, low priority)."""
    if isinstance(entry, str):
        return *_tm_variant(entry), None, False
    unknown = set(entry) - {"spec", "stretch_demand", "low_priority"}
    if unknown or "spec" not in entry:
        raise ValueError(f"grid.tm entry {entry}: needs 'spec', optional 'stretch_demand' and 'low_priority' (unknown: {sorted(unknown)})")
    sds = {float(s) for s in entry["stretch_demand"]} if "stretch_demand" in entry else None
    return *_tm_variant(entry["spec"]), sds, bool(entry.get("low_priority", False))


def _resources(cfg: dict, res_class: str, dataset: str) -> dict:
    """[resources.<class>] default, overridden by its <dataset> entry; truth-original falls back to the 'full' class."""
    res_cfg = cfg["resources"]
    if res_class not in res_cfg and res_class == "truth-original":
        res_class = "full"
    section = res_cfg[res_class]
    flat = {k: v for k, v in section.items() if not isinstance(v, dict)}
    res = {**section.get("default", {}), **flat, **section.get(dataset, {})}
    missing = {"cpus", "mem", "time"} - res.keys()
    if missing:
        raise ValueError(f"[resources.{res_class}] for '{dataset}' lacks {sorted(missing)}")
    return {"cpus": int(res["cpus"]), "mem": str(res["mem"]), "time": str(res["time"])}


def _dataset_codes(datasets: list[str]) -> dict:
    """{dataset folder name: 2-character job-name code} (first two letters/digits, upper case), unique per run."""
    codes = {}
    for dataset in datasets:
        name = Path(dataset).name
        codes[name] = re.sub(r"[^A-Za-z0-9]", "", name)[:2].upper().ljust(2, "X")
    clashes = {c for c in codes.values() if list(codes.values()).count(c) > 1}
    if clashes:
        raise ValueError(f"grid.datasets: job-name codes {sorted(clashes)} are not unique ({codes}) - rename a dataset folder "
                         f"or extend _dataset_codes")
    return codes


def build_plan(cfg: dict) -> dict:
    """All tasks of the config: {key: {key, group, index, cmd, res, deps}}. Tasks of one group (= one job array) share
    task kind, edge handling and dataset (hence resources); within a dataset every grid point has the same index in
    all its groups, so array dependencies can use aftercorr (task i waits for task i)."""
    grid, markov = cfg["grid"], cfg.get("markov", {})
    tasks = sorted(grid["tasks"], key=GRID_TASKS.index)
    for task in tasks:
        for dep_task, _ in TASK_DEPS[task]:
            if dep_task not in tasks:
                raise ValueError(f"grid.tasks: '{task}' needs '{dep_task}'")
    edges = grid["edges"]
    tms = [_tm_entry(t) for t in grid["tm"]]
    stretch = [float(s) for s in grid.get("stretch_demand", [1.0])]
    for label, _, sds, _ in tms:
        if sds is not None and not sds <= set(stretch):
            raise ValueError(f"grid.tm '{label}': stretch_demand {sorted(sds - set(stretch))} not in grid.stretch_demand")
    clusters = [int(c) for c in grid["clusters"]]

    solver_args = ["--threads", "@THREADS@"]
    if markov.get("node_file_start") is not None and markov.get("node_file_start_fraction") is not None:
        raise ValueError("[markov]: set either node_file_start or node_file_start_fraction, not both")
    if markov.get("node_file_start") is not None:
        solver_args += ["--node-file-start", str(markov["node_file_start"]), "--node-file-dir", "@NODEDIR@"]
    elif markov.get("node_file_start_fraction") is not None:
        if not 0 < float(markov["node_file_start_fraction"]) <= 1:
            raise ValueError("[markov] node_file_start_fraction must be in (0, 1]")
        solver_args += ["--node-file-start", "@NODEFILESTART@", "--node-file-dir", "@NODEDIR@"]  # set by the job script

    def markov_cmd(dataset, sd, *extra):
        cmd = ["python", "research/MK/Markov.py", dataset, "--reuse-inputfiles", "--no-overwrite", "--debug", *markov.get("args", [])]
        if sd != 1.0:
            cmd += ["--stretch-demand", f"{sd:g}"]
        return cmd + list(extra)

    plan = {}
    ds_codes = _dataset_codes(grid["datasets"])
    rank = {name: i for i, name in enumerate(ds_codes)}  # scheduling preference among the own jobs = grid.datasets order

    def add(key, group, index, cmd, res, deps, dataset=None, task=None, edge=None, low=False):
        bad = [a for a in cmd if re.search(r"[\s'\"\\]", a)]
        if bad:
            raise ValueError(f"Arguments must not contain whitespace or quotes (the job script splits on whitespace): {bad}")
        # Low-priority tasks: lower-case dataset code (tells their arrays apart in squeue), ranked after all datasets
        code = ds_codes.get(dataset, "")
        jobname = group if dataset is None else f"{code.lower() if low else code}{TASK_CODES[task]}{EDGE_CODES.get(edge, edge and edge[:2])}_{group}"
        task_rank = rank.get(dataset, 0) + (len(rank) if low else 0)  # evaluate (no dataset): 0
        plan[key] = {"key": key, "group": group, "jobname": jobname, "rank": task_rank, "index": index, "cmd": " ".join(cmd), "res": res, "deps": deps}

    for dataset in grid["datasets"]:
        name = Path(dataset).name
        for si, sd in enumerate(stretch, 1):
            prefix = f"{name}/sd{sd:g}"
            add(f"{prefix}/prepare", f"prepare-{name}", si,
                markov_cmd(dataset, sd, "--clusters", ",".join(map(str, clusters)), "--prepare-only"),
                _resources(cfg, "prepare", name), [], name, "prepare")
            if grid.get("truth_original", False):
                add(f"{prefix}/truth-original", f"truth-original-{name}", si, markov_cmd(dataset, sd, *solver_args, "--task", "truth-original"),
                    _resources(cfg, "truth-original", name), [f"{prefix}/prepare"], name, "truth-original")

        # Grid points longest first: high cluster counts, then the TM variants in config order (base first). Low-priority
        # TM variants form their own job arrays (one --nice per array) with their own index sequence.
        points = sorted(((si, c, ti) for si, c, ti in itertools.product(range(len(stretch)), clusters, range(len(tms)))
                         if tms[ti][2] is None or stretch[si] in tms[ti][2]), key=lambda p: (-p[1], p[2], p[0]))
        for low in (False, True):
            for gi, (si, c, ti) in enumerate([p for p in points if tms[p[2]][3] == low], 1):
                sd, (tm_label, tm_args, _, _) = stretch[si], tms[ti]
                prefix = f"{name}/sd{sd:g}/c{c}/{tm_label}"
                for task in tasks:
                    if task in ORIGINAL_TASKS and tm_label != "base":
                        continue
                    for edge in (["Truth"] if task in TRUTH_TASKS else []) + edges:
                        deps = [f"{prefix}/{t}/{edge if e == 'EDGE' else e}" for t, e in TASK_DEPS[task]] or [f"{name}/sd{sd:g}/prepare"]
                        res_class = "rp" if task in ("main", "operational") and edge != "Truth" else "full"
                        add(f"{prefix}/{task}/{edge}", f"{task}-{edge}-{name}" + ("-low" if low else ""), gi,
                            markov_cmd(dataset, sd, *solver_args, "--clusters", str(c), *tm_args, "--task", task, "--edge", edge),
                            _resources(cfg, res_class, name), deps, name, task, edge, low)

    # Work units / solver times are compared between edge handlings and Truth: all solves of a dataset need the same threads
    for dataset in grid["datasets"]:
        name = Path(dataset).name
        cpus = {t["res"]["cpus"] for t in plan.values() if t["key"].startswith(f"{name}/") and not t["key"].endswith("/prepare")}
        if len(cpus) > 1:
            raise ValueError(f"[resources]: the solves of '{name}' use different cpus {sorted(cpus)} - set the same cpus for rp, full "
                             f"and truth-original, otherwise work units and solver times are not comparable")

    evaluate = cfg.get("evaluate")
    if evaluate is not None:
        cmd = ["python", "research/MK/EvaluateMarkov.py", *evaluate.get("args", ["all", "--no-show"])]
        if evaluate.get("output_dir"):
            cmd += ["--output-dir", evaluate["output_dir"]]
        add("evaluate", "evaluate", 1, cmd, _resources(cfg, "evaluate", "evaluate"), [])

    # squeue shows 8 characters of the job name: they must tell the job arrays apart
    heads = {}
    for t in plan.values():
        heads.setdefault(t["jobname"][:8], set()).add(t["group"])
    clashes = {h: sorted(g) for h, g in heads.items() if len(g) > 1}
    if clashes:
        raise ValueError(f"Job names not distinguishable by their first 8 characters: {clashes} - extend TASK_CODES/EDGE_CODES")
    return plan


def group_tasks(plan: dict) -> dict:
    """{group: [task, ...]} in plan (= dependency) order."""
    groups = {}
    for task in plan.values():
        groups.setdefault(task["group"], []).append(task)
    return groups


def group_dependency(plan: dict, members: list) -> str | None:
    """Slurm --dependency of a job array: aftercorr on parent groups whose task i the task i depends on, afterok on
    whole parent groups otherwise (prepare). Parent groups are referenced as '@group' and resolved at submission."""
    same_index = {}  # parent group -> every dependency into it has the dependent task's own index
    for task in members:
        for dep in task["deps"]:
            parent = plan[dep]
            same_index[parent["group"]] = same_index.get(parent["group"], True) and parent["index"] == task["index"]
    corr = [g for g, same in same_index.items() if same]
    whole = [g for g, same in same_index.items() if not same]
    parts = ([f"aftercorr:{':'.join('@' + g for g in corr)}"] if corr else []) + ([f"afterok:{':'.join('@' + g for g in whole)}"] if whole else [])
    return ",".join(parts) or None


def compress_indices(indices: list[int]) -> str:
    """[1, 2, 3, 7] -> '1-3,7'."""
    out = []
    for _, run in itertools.groupby(enumerate(sorted(indices)), lambda p: p[1] - p[0]):
        run = [i for _, i in run]
        out.append(f"{run[0]}-{run[-1]}" if len(run) > 1 else str(run[0]))
    return ",".join(out)


########################################################################################################################
# Slurm interaction
########################################################################################################################

class Slurm:
    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self._dry_id = 0

    def sbatch(self, args: list[str]) -> str:
        cmd = ["sbatch", "--parsable", *args]
        if self.dry_run:
            self._dry_id += 1
            print("  " + " ".join(cmd))
            return f"DRY{self._dry_id}"
        out = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout.strip()
        return out.split(";")[0]

    def scancel(self, job_ids: list[str]) -> None:
        if not job_ids:
            return
        if self.dry_run:
            print("  scancel " + " ".join(job_ids))
            return
        for i in range(0, len(job_ids), 200):
            subprocess.run(["scancel", *job_ids[i:i + 200]], check=False)

    def renice(self, nice_jobs: dict[int, list[str]]) -> None:
        """scontrol update Nice of queued jobs, {nice: [job id, ...]} (an array id covers the array's pending tasks)."""
        for nice, job_ids in nice_jobs.items():
            for i in range(0, len(job_ids), 200):
                cmd = ["scontrol", "update", f"JobId={','.join(job_ids[i:i + 200])}", f"Nice={nice}"]
                if self.dry_run:
                    print("  " + " ".join(cmd))
                    continue
                out = subprocess.run(cmd, capture_output=True, text=True)
                if out.returncode != 0:
                    print(f"  warning: setting Nice={nice} failed ({(out.stderr or out.stdout).strip()})")

    @staticmethod
    def query(job_ids: set[str]) -> dict:
        """{job id ('A_i' or 'J'): {state, reason, exit, elapsed, maxrss_mb, reqmem}} from squeue (queued/running,
        array tasks expanded) and sacct (everything that started)."""
        info = {}
        parents = sorted({j.split("_")[0] for j in job_ids if not j.startswith("DRY")})
        if not parents:
            return info
        for i in range(0, len(parents), 200):
            out = subprocess.run(["sacct", "-n", "-P", "-j", ",".join(parents[i:i + 200]),
                                  "--format=JobID,State,ExitCode,Elapsed,MaxRSS,ReqMem"], capture_output=True, text=True).stdout
            for line in out.splitlines():
                job, state, exit_code, elapsed, maxrss, reqmem = (line.split("|") + [""] * 6)[:6]
                if "[" in job:
                    continue  # still-pending part of an array: squeue has the expanded tasks
                base, _, step = job.partition(".")
                entry = info.setdefault(base, {})
                if step:
                    rss = _mem_mb(maxrss)
                    if rss is not None:
                        entry["maxrss_mb"] = max(entry.get("maxrss_mb", 0), rss)
                else:
                    entry.update(state=state.split()[0], exit=exit_code, elapsed=elapsed, reqmem=reqmem)
        user = os.environ.get("USER", "")
        out = subprocess.run(["squeue", "-h", "-r", "-u", user, "-o", "%i|%T|%r"], capture_output=True, text=True).stdout
        for line in out.splitlines():
            job, state, reason = (line.split("|") + ["", ""])[:3]
            if job.split("_")[0] in parents:
                info.setdefault(job, {}).update(state=state, reason=reason)
        return info


def _mem_mb(value: str) -> float | None:
    m = re.fullmatch(r"([\d.]+)([KMGT]?)n?c?", value.strip())
    if not m:
        return None
    return float(m.group(1)) * {"": 1 / 1024 ** 2, "K": 1 / 1024, "M": 1, "G": 1024, "T": 1024 ** 2}[m.group(2)]


def _fmt_mem(mb: float) -> str:
    return f"{mb / 1024:.0f}G" if mb >= 10 * 1024 else f"{mb:.0f}M"


def _scale_mem(mem: str, factor: float) -> str:
    return _fmt_mem(_mem_mb(mem.upper().removesuffix("B")) * factor)


########################################################################################################################
# Run state
########################################################################################################################

def run_dir(name_or_config: str) -> Path:
    path = Path(name_or_config)
    name = tomllib.loads(path.read_text())["name"] if path.is_file() else name_or_config
    return RUNS_DIR / name


def load_state(name_or_config: str) -> tuple[Path, dict]:
    rdir = run_dir(name_or_config)
    if not (rdir / "state.json").exists():
        sys.exit(f"No submitted run in '{rdir}' (submit it first)")
    return rdir, json.loads((rdir / "state.json").read_text())


def save_state(rdir: Path, state: dict) -> None:
    tmp = rdir / "state.json.tmp"
    tmp.write_text(json.dumps(state, indent=1))
    tmp.replace(rdir / "state.json")


def _now() -> str:
    return datetime.datetime.now().isoformat(timespec="seconds")


def current_job(task: dict) -> str | None:
    return task["attempts"][-1]["job"] if task["attempts"] else None


def nice(task: dict, step: int) -> int:
    """sbatch --nice of a task: rank (grid.datasets order, low-priority TM variants after all datasets) x nice_step. A positive
    nice is the only way to order the own jobs without operator rights; it costs the same against other users' jobs."""
    return task.get("rank", 0) * step


def _nice_step(value) -> int:
    step = int(value)
    if step < 0:
        sys.exit("nice_step must be >= 0 (a negative nice needs operator rights)")
    return step


def prioritize(state: dict, keys, slurm: "Slurm") -> None:
    """Re-apply the nice of the given (queued) tasks' jobs, e.g. after changing nice_step. Array jobs go in by array id."""
    nice_jobs = {}
    for key in keys:
        job = current_job(state["tasks"][key])
        job = job and job.split("_")[0]
        jobs = nice_jobs.setdefault(nice(state["tasks"][key], state.get("nice_step", DEFAULT_NICE_STEP)), [])
        if job and job not in jobs:
            jobs.append(job)
    if not nice_jobs:
        print("No queued jobs")
        return
    print(f"Setting the nice of {sum(map(len, nice_jobs.values()))} queued job(s) / array(s): "
          + ", ".join(f"{len(j)} x {n}" for n, j in sorted(nice_jobs.items())))
    slurm.renice(nice_jobs)


def classify(state: dict, info: dict) -> dict:
    """{key: (category, slurm info)}. A task whose job is pending on a dependency that can never be satisfied, or that
    was cancelled while an ancestor failed, counts as blocked."""
    result = {}
    for key, task in state["tasks"].items():
        job = current_job(task)
        entry = info.get(job, {}) if job else {}
        st = entry.get("state", "")
        if st == "COMPLETED":
            cat = DONE
        elif st in _RUNNING_STATES:
            cat = RUNNING
        elif st == "PENDING":
            cat = BLOCKED if "DependencyNeverSatisfied" in entry.get("reason", "") else PENDING
        elif st in _FAILED_STATES:
            cat = FAILED
        else:
            cat = UNKNOWN
        result[key] = [cat, entry]
    for key in state["tasks"]:  # cancelled because of a failed ancestor -> blocked (kill_invalid_depend clusters)
        if result[key][0] == FAILED and result[key][1].get("state") == "CANCELLED" and failed_ancestors(state, result, key):
            result[key][0] = BLOCKED
    return result


def failed_ancestors(state: dict, status: dict, key: str) -> list[str]:
    found, stack, seen = [], list(state["tasks"][key]["deps"]), set()
    while stack:
        dep = stack.pop()
        if dep in seen:
            continue
        seen.add(dep)
        if status[dep][0] == FAILED and status[dep][1].get("state") != "CANCELLED":
            found.append(dep)
        else:
            stack.extend(state["tasks"][dep]["deps"])
    return found


def descendants(state: dict, keys: set[str]) -> list[str]:
    """All tasks depending (transitively) on keys, in plan order (excluding keys and evaluate)."""
    children = {}
    for key, task in state["tasks"].items():
        for dep in task["deps"]:
            children.setdefault(dep, []).append(key)
    found, stack = set(), list(keys)
    while stack:
        for child in children.get(stack.pop(), []):
            if child not in found and child not in keys:
                found.add(child)
                stack.append(child)
    return [k for k in state["tasks"] if k in found]


########################################################################################################################
# Commands
########################################################################################################################

def cmd_submit(args) -> None:
    cfg = tomllib.loads(Path(args.config).read_text())
    rdir = RUNS_DIR / cfg["name"]
    if (rdir / "state.json").exists() and not args.dry_run:
        sys.exit(f"'{rdir}' already holds a submitted run - use status/restart, or delete the folder to start over")
    plan = build_plan(cfg)
    groups = group_tasks(plan)

    slurm_cfg = cfg["slurm"]
    nice_step = _nice_step(slurm_cfg.get("nice_step", DEFAULT_NICE_STEP))
    # Mail address from the config or $MK_MAIL_USER (keeps it out of the repo); without one, no mails are requested
    mail_user = slurm_cfg.get("mail_user") or os.environ.get("MK_MAIL_USER", "")
    mail = f"#SBATCH --mail-type={slurm_cfg.get('mail_type', 'FAIL')}\n#SBATCH --mail-user={mail_user}\n" if mail_user else ""
    # node_file_start_fraction: computed in the job from the granted memory, so it follows restart --mem / --mem-factor
    fraction = cfg.get("markov", {}).get("node_file_start_fraction")
    node_file_start = NODE_FILE_START_TEMPLATE.format(fraction=float(fraction)) if fraction is not None else ""
    script = SBATCH_TEMPLATE.format(node_file_start=node_file_start, account=slurm_cfg["account"], partition=slurm_cfg["partition"], qos=slurm_cfg.get("qos", slurm_cfg["partition"]), mail=mail,
                                    setup=slurm_cfg.get("setup", "").strip(), repo=slurm_cfg["repo"])
    out_dir = rdir if not args.dry_run else rdir.with_name(rdir.name + "-dryrun")
    (out_dir / "logs").mkdir(parents=True, exist_ok=True)
    (out_dir / "commands").mkdir(exist_ok=True)
    (out_dir / "task.sbatch").write_text(script, newline="\n")
    if cfg.get("evaluate", {}).get("output_dir"):
        Path(cfg["evaluate"]["output_dir"]).mkdir(parents=True, exist_ok=True)

    state = {"config": str(Path(args.config).resolve()), "created": _now(), "rundir": str(out_dir.resolve()),
             "mail": bool(mail_user), "nice_step": nice_step, "tasks": {k: {**t, "attempts": []} for k, t in plan.items()}, "groups": {}}
    slurm = Slurm(dry_run=args.dry_run)
    print(f"{len(plan)} tasks in {len(groups)} job arrays")
    for group, members in groups.items():
        cmd_file = out_dir / "commands" / f"{group}.tsv"
        cmd_file.write_text("".join(f"{t['index']}\t{t['key']}\t{t['cmd']}\n" for t in members), newline="\n")
        res = members[0]["res"]
        if group == "evaluate":
            dependency = "afterany:" + ":".join(g["job"] for g in state["groups"].values())
            sbatch_args = ["--export=ALL,TASK_INDEX=1", f"--output={out_dir / 'logs' / 'evaluate_%j.out'}", *(["--mail-type=END,FAIL"] if mail_user else [])]
        else:
            dependency = group_dependency(plan, members)
            if dependency:
                dependency = re.sub(r"@([^:,]+)", lambda m: state["groups"][m.group(1)]["job"], dependency)
            sbatch_args = [f"--array={compress_indices([t['index'] for t in members])}", f"--output={out_dir / 'logs' / (group + '_%A_%a.out')}"]
        job = slurm.sbatch([f"--job-name={members[0]['jobname']}", f"--cpus-per-task={res['cpus']}", f"--mem={res['mem']}",
                            f"--time={res['time']}", f"--nice={nice(members[0], nice_step)}", *sbatch_args, *([f"--dependency={dependency}"] if dependency else []), str(out_dir / "task.sbatch"), str(cmd_file)])
        state["groups"][group] = {"job": job, "cmdfile": str(cmd_file)}
        for t in members:
            task_job, log = (job, out_dir / "logs" / f"evaluate_{job}.out") if group == "evaluate" else \
                (f"{job}_{t['index']}", out_dir / "logs" / f"{group}_{job}_{t['index']}.out")
            state["tasks"][t["key"]]["attempts"].append({"job": task_job, "log": str(log), "res": res, "time": _now()})
        save_state(out_dir, state)  # after every array, so a failed submission can be inspected / cancelled
    print(f"State: {out_dir / 'state.json'}" + ("  (dry run: nothing submitted)" if args.dry_run else ""))


def cmd_status(args) -> None:
    rdir, state = load_state(args.run)
    status = classify(state, Slurm.query({current_job(t) for t in state["tasks"].values() if current_job(t)}))

    def kind(key):
        return "/".join(key.split("/")[-2:]) if "/c" in key else key.split("/")[-1]  # e.g. 'regret/Markov', 'prepare'

    counts = {}
    for key, (cat, _) in status.items():
        counts.setdefault(kind(key), dict.fromkeys(CATEGORIES, 0))[cat] += 1
    width = max(len(k) for k in counts)
    print(f"{'task':<{width}}  {'total':>6}" + "".join(f"  {c:>8}" for c in CATEGORIES))
    for k, row in counts.items():
        print(f"{k:<{width}}  {sum(row.values()):>6}" + "".join(f"  {row[c] or '':>8}" for c in CATEGORIES))
    totals = {c: sum(r[c] for r in counts.values()) for c in CATEGORIES}
    print(f"{'TOTAL':<{width}}  {len(status):>6}" + "".join(f"  {totals[c]:>8}" for c in CATEGORIES))

    def line(key, entry):
        task = state["tasks"][key]
        rss = entry.get("maxrss_mb")
        mem = f"mem {_fmt_mem(rss)}/{task['attempts'][-1]['res']['mem']}" if rss else ""
        return (f"  {key:<55} {entry.get('state', '?'):<14} exit {entry.get('exit', '-'):<6} {entry.get('elapsed', ''):>11} {mem:<16}"
                f" job {current_job(task)}  (attempt {len(task['attempts'])})\n      log: {task['attempts'][-1]['log']}")

    shown = [args.list] if args.list else [FAILED, BLOCKED, UNKNOWN]
    for cat in shown:
        keys = [k for k, (c, _) in status.items() if c == cat and (args.filter is None or fnmatch.fnmatch(k, args.filter))]
        if not keys:
            continue
        print(f"\n{cat.upper()} ({len(keys)})")
        if cat == BLOCKED and not args.list:  # group by the failed task they wait for
            by_root = {}
            for k in keys:
                for root in failed_ancestors(state, status, k) or ["(unknown)"]:
                    by_root.setdefault(root, []).append(k)
            for root, ks in by_root.items():
                print(f"  {len(ks):>4} task(s) waiting for {root}")
        else:
            for k in keys:
                print(line(k, status[k][1]))
    if not args.list:
        print("\nRestart failed tasks (and the tasks waiting for them): cluster.py restart <run> --failed [--mem-factor 1.5]")


def cmd_restart(args) -> None:
    rdir, state = load_state(args.run)
    tasks = state["tasks"]
    status = classify(state, Slurm.query({current_job(t) for t in tasks.values() if current_job(t)}))
    restartable = {FAILED, BLOCKED, UNKNOWN} | ({PENDING} if args.include_pending else set())

    selected = [k for k in tasks if k != "evaluate" and status[k][0] in restartable and
                ((args.failed and status[k][0] == FAILED) or any(fnmatch.fnmatch(k, p) for p in args.patterns))]
    skipped = [k for k in tasks if any(fnmatch.fnmatch(k, p) for p in args.patterns) and k not in selected and k != "evaluate"]
    if skipped:
        print(f"Not restarting {len(skipped)} matching task(s) that are {sorted({status[k][0] for k in skipped})} "
              f"(done runs are skipped by --no-overwrite anyway; delete the .sqlite to recompute; queued ones need --include-pending)")
    if not selected:
        sys.exit("Nothing to restart")
    # Everything downstream that has not finished must be resubmitted too: its old jobs wait for the old (failed) ones
    follow = [k for k in descendants(state, set(selected)) if status[k][0] in {PENDING, BLOCKED, FAILED, UNKNOWN}]
    resubmit = [k for k in tasks if k in set(selected) | set(follow)]  # plan order = dependency order
    print(f"Restarting {len(selected)} task(s) + {len(follow)} dependent task(s)")
    if args.cpus:
        print(f"  warning: --cpus {args.cpus} makes the work units / solver times of the restarted tasks incomparable to the other "
              f"solves of their dataset (prefer --mem / --time)")

    slurm = Slurm(dry_run=args.dry_run)
    nice_step = state.get("nice_step", DEFAULT_NICE_STEP)
    slurm.scancel([current_job(tasks[k]) for k in resubmit if status[k][0] in {PENDING, BLOCKED}])
    new_jobs = {}
    for key in resubmit:
        task = tasks[key]
        res = dict(task["attempts"][-1]["res"])
        if key in selected:
            if args.mem:
                res["mem"] = args.mem
            elif args.mem_factor:
                res["mem"] = _scale_mem(res["mem"], args.mem_factor)
            if args.cpus:
                res["cpus"] = args.cpus
            if args.time:
                res["time"] = args.time
        deps = []
        for dep in task["deps"]:
            if dep in new_jobs:
                deps.append(new_jobs[dep])
            elif status[dep][0] != DONE:
                if status[dep][0] not in {RUNNING, PENDING}:
                    print(f"  warning: {key} depends on {dep} ({status[dep][0]}), which is not restarted - it will not start")
                deps.append(current_job(tasks[dep]))
        group = task["group"]
        job = slurm.sbatch([f"--job-name={task.get('jobname', group)}", f"--cpus-per-task={res['cpus']}", f"--mem={res['mem']}",
                            f"--time={res['time']}", f"--nice={nice(task, nice_step)}", f"--export=ALL,TASK_INDEX={task['index']}", f"--output={Path(state['rundir']) / 'logs' / (group + '_%j.out')}",
                            *([f"--dependency=afterok:{':'.join(deps)}"] if deps else []),
                            str(Path(state["rundir"]) / "task.sbatch"), state["groups"][group]["cmdfile"]])
        new_jobs[key] = job
        task["attempts"].append({"job": job, "log": str(Path(state["rundir"]) / "logs" / f"{group}_{job}.out"), "res": res, "time": _now()})

    # Evaluation must wait for the new jobs too
    if "evaluate" in tasks and status["evaluate"][0] not in {DONE, RUNNING}:
        if status["evaluate"][0] in {PENDING, BLOCKED}:
            slurm.scancel([current_job(tasks["evaluate"])])
        active = [current_job(t) for k, t in tasks.items() if k != "evaluate" and (k in new_jobs or status[k][0] in {PENDING, RUNNING})]
        active = sorted({j.split("_")[0] if "_" in j else j for j in active})
        ev = tasks["evaluate"]
        res = ev["attempts"][-1]["res"]
        job = slurm.sbatch(["--job-name=evaluate", f"--cpus-per-task={res['cpus']}", f"--mem={res['mem']}", f"--time={res['time']}",
                            "--export=ALL,TASK_INDEX=1", f"--output={Path(state['rundir']) / 'logs' / 'evaluate_%j.out'}", *(["--mail-type=END,FAIL"] if state.get("mail", True) else []),
                            *([f"--dependency=afterany:{':'.join(active)}"] if active else []),
                            str(Path(state["rundir"]) / "task.sbatch"), state["groups"]["evaluate"]["cmdfile"]])
        ev["attempts"].append({"job": job, "log": str(Path(state["rundir"]) / "logs" / f"evaluate_{job}.out"), "res": res, "time": _now()})
    if not args.dry_run:
        save_state(rdir, state)


def cmd_prioritize(args) -> None:
    rdir, state = load_state(args.run)
    if args.nice_step is not None:
        state["nice_step"] = _nice_step(args.nice_step)  # also used by later restarts
    status = classify(state, Slurm.query({current_job(t) for t in state["tasks"].values() if current_job(t)}))
    prioritize(state, [k for k in state["tasks"] if k != "evaluate" and status[k][0] == PENDING], Slurm(dry_run=args.dry_run))
    if args.nice_step is not None and not args.dry_run:
        save_state(rdir, state)


def cmd_log(args) -> None:
    _, state = load_state(args.run)
    matches = [k for k in state["tasks"] if fnmatch.fnmatch(k, args.key)]
    if len(matches) != 1:
        sys.exit(f"'{args.key}' matches {len(matches)} tasks" + (f": {matches[:10]}" if matches else ""))
    task = state["tasks"][matches[0]]
    for attempt in task["attempts"]:
        print(f"attempt job {attempt['job']} ({attempt['time']}, {attempt['res']}): {attempt['log']}")
    log = Path(task["attempts"][-1]["log"])
    if log.exists():
        print(f"\n--- last {args.lines} lines of {log} ---")
        print("\n".join(log.read_text(errors="replace").splitlines()[-args.lines:]))
    else:
        print("(log does not exist yet)")


def cmd_cancel(args) -> None:
    _, state = load_state(args.run)
    jobs = sorted({g["job"] for g in state["groups"].values()} |
                  {a["job"] for t in state["tasks"].values() for a in t["attempts"] if "_" not in a["job"]})
    print(f"Cancelling {len(jobs)} job(s) / array(s)")
    Slurm().scancel(jobs)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("submit", help="Submit all tasks of a config as job arrays with dependencies")
    p.add_argument("config", help="TOML experiment file, e.g. research/MK/experiments/experiment.toml")
    p.add_argument("--dry-run", action="store_true", help="Print the sbatch calls and write the files to runs/<name>-dryrun/ without submitting")
    p.set_defaults(func=cmd_submit)
    p = sub.add_parser("status", help="Task counts per kind and state; lists failed / blocked tasks")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("--list", choices=CATEGORIES, help="List all tasks in this state instead")
    p.add_argument("--filter", help="Only list tasks matching this glob pattern, e.g. 'TX-123BT/*'")
    p.set_defaults(func=cmd_status)
    p = sub.add_parser("restart", help="Resubmit failed tasks (and everything waiting for them)")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("patterns", nargs="*", default=[], help="Glob patterns of task keys, e.g. 'TX-123BT/sd0.5/c21/base/main/Truth' or 'TX-123BT/*/regret/*'")
    p.add_argument("--failed", action="store_true", help="Select all failed tasks")
    p.add_argument("--include-pending", action="store_true", help="Also resubmit matching tasks that are still queued (e.g. to change their resources)")
    p.add_argument("--mem", help="New memory for the selected tasks, e.g. 200G")
    p.add_argument("--mem-factor", type=float, help="Scale the memory of the selected tasks, e.g. 1.5")
    p.add_argument("--cpus", type=int, help="New core count for the selected tasks")
    p.add_argument("--time", help="New time limit for the selected tasks, e.g. 3-00:00:00")
    p.add_argument("--dry-run", action="store_true", help="Print what would be cancelled / submitted")
    p.set_defaults(func=cmd_restart)
    p = sub.add_parser("prioritize", help="Re-apply the nice (rank x nice_step) of the queued jobs, e.g. with a new --nice-step")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("--nice-step", type=int, help="New nice per rank, stored for later restarts (default: the run's nice_step)")
    p.add_argument("--dry-run", action="store_true", help="Print the scontrol calls only")
    p.set_defaults(func=cmd_prioritize)
    p = sub.add_parser("log", help="Attempts and log tail of one task")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("key", help="Task key (glob allowed if it matches exactly one task)")
    p.add_argument("-n", "--lines", type=int, default=40)
    p.set_defaults(func=cmd_log)
    p = sub.add_parser("cancel", help="Cancel all jobs of a run")
    p.add_argument("run", help="Run name or its TOML file")
    p.set_defaults(func=cmd_cancel)
    args = parser.parse_args()
    if args.command == "restart" and not (args.failed or args.patterns):
        parser.error("restart needs --failed and/or task patterns")
    args.func(args)


if __name__ == "__main__":
    main()
