"""Run an MK experiment grid on a Slurm cluster - one job per solve (submit) or whole-node workers of a task pool
(submit-workers, pool.py) - or locally (see README.md, section "Cluster runs").

    python research/MK/cluster.py submit   research/MK/experiments/experiment.toml [--dry-run]
    python research/MK/cluster.py status   experiment [--list STATE] [--filter PATTERN]
    python research/MK/cluster.py restart  experiment [PATTERN ...] [--failed] [--mem 200G | --mem-factor 1.5] [--cpus N] [--time T]
    python research/MK/cluster.py prioritize experiment [--nice-step N]
    python research/MK/cluster.py resources experiment [--mem-factor 1.3] [--time-factor 2]
    python research/MK/cluster.py log      experiment KEY
    python research/MK/cluster.py cancel   experiment
    python research/MK/cluster.py submit-workers experiment [--workers N] [--estimate-only] [--dry-run]
    python research/MK/cluster.py worker   experiment [PATTERN ...] [--cores N] [--mem 700G] [--hours H]
    python research/MK/cluster.py local    experiment PATTERN ... [--jobs N] [--with-deps] [--keep-going] [--log-dir DIR] [--dry-run]

Run from the repo root on the login node (`local`: on any machine, with the conda env active). Standard library only (Python >= 3.11 for tomllib).
"""
import argparse
import datetime
import fnmatch
import itertools
import json
import os
import re
import subprocess
import sys
import shutil
import tempfile
import time
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    sys.exit("cluster.py needs Python >= 3.11 (tomllib)")

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import pool  # noqa: E402  (research/MK/pool.py, standard library only)

RUNS_DIR = HERE / "runs"
DEFAULT_NICE_STEP = 100  # [slurm] nice_step: sbatch --nice per rank (MUSICA age weight 10000 per 14 days = ~30 per hour)

# Grid tasks in dependency order (a task only depends on tasks listed before it)
GRID_TASKS = ["main", "operational", "regret", "invest-regret", "operational-regret", "original-invest-regret", "original-regret"]
TRUTH_TASKS = {"main", "operational", "original-invest-regret"}  # tasks that also exist for the Truth edge handling
ORIGINAL_TASKS = {"original-invest-regret", "original-regret"}  # only for the unshifted transition matrix
TASK_DEPS = {  # (task, edge) -> [(task, edge)] within the same grid point; "EDGE" = the task's own edge
    "main": [],
    "operational": [("main", "Truth")],
    "regret": [("main", "EDGE")],
    "invest-regret": [("main", "EDGE")],
    "operational-regret": [("main", "Truth"), ("operational", "EDGE")],
    "original-invest-regret": [("main", "EDGE")],
    "original-regret": [("main", "EDGE")],
}

# Job names: squeue shows only the first 8 characters, so every job name starts with an 8-character code
# <dataset 2><task 4><edge 2> (e.g. 'TXmainMk', 'NRoRgrTr'), followed by '_' and the full group name
TASK_CODES = {"main": "main", "operational": "oper", "regret": "rgrt", "invest-regret": "iRgr", "operational-regret": "oRgr",
              "original-invest-regret": "OiRg", "original-regret": "ORgr", "prepare": "prep", "truth-original": "trOr"}
EDGE_CODES = {"Truth": "Tr", "NoEnf": "NE", "Cyclic": "Cy", "Markov": "Mk", None: "--"}

# Slurm state -> category shown by `status`
DONE, RUNNING, PENDING, BLOCKED, FAILED, UNKNOWN = "done", "running", "pending", "blocked", "failed", "unknown"
CATEGORIES = [DONE, RUNNING, PENDING, BLOCKED, FAILED, UNKNOWN]
_FAILED_STATES = {"FAILED", "OUT_OF_MEMORY", "TIMEOUT", "CANCELLED", "NODE_FAIL", "PREEMPTED", "BOOT_FAIL", "DEADLINE"}
_RUNNING_STATES = {"RUNNING", "COMPLETING", "CONFIGURING", "SUSPENDED", "REQUEUED", "RESIZING"}

DEFAULT_DISK_MIN_FREE_GB = 10  # [slurm] / [pool] disk_min_free_gb: warn (pool: start no new tasks) below this free space

# Whole-node worker job of the task pool (submit-workers); the worker submits its successor itself (chaining)
WORKER_SBATCH_TEMPLATE = """#!/bin/bash
#ASC --vanilla
#SBATCH -A {account}
#SBATCH -p {partition}
#SBATCH --qos={qos}
#SBATCH -N 1
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --time={walltime}
#SBATCH --job-name={jobname}
#SBATCH --output={jobs_dir}/worker_%j.out
{mail}# Generated by research/MK/cluster.py submit-workers - one whole-node worker of the task pool of {name}.
# After {chain_hours:g} h it submits this script again (if tasks remain), so the successor queues while it still runs.
set -eo pipefail
echo "Worker job $SLURM_JOB_ID on $SLURM_JOB_NODELIST, $(date +%FT%T)"

{setup}

cd "{repo}"
python research/MK/cluster.py worker "{config}" --cores {cores} --mem {mem} --chain-after-hours {chain_hours:g} --chain-script "{script}"
"""

SBATCH_TEMPLATE = """#!/bin/bash
#ASC --vanilla
#SBATCH -A {account}
#SBATCH -p {partition}
#SBATCH --qos={qos}
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --threads-per-core=1
{mail}# Generated by research/MK/cluster.py - runs task $TASK_INDEX (restart) or $SLURM_ARRAY_TASK_ID (array) of the command file $1.
set -eo pipefail

IDX="${{TASK_INDEX:-$SLURM_ARRAY_TASK_ID}}"
KEY=$(awk -F'\\t' -v i="$IDX" '$1 == i {{print $2; exit}}' "$1")
CMD=$(awk -F'\\t' -v i="$IDX" '$1 == i {{print $3; exit}}' "$1")
[ -n "$CMD" ] || {{ echo "No task $IDX in $1"; exit 1; }}

# Gurobi threads = allocated cores (Gurobi's default would use every CPU of the node); node files to node-local scratch
NODE_DIR="${{TMPDIR:-/tmp}}/gurobi-nodes-${{SLURM_JOB_ID}}"
mkdir -p "$NODE_DIR"
CMD="${{CMD//@THREADS@/$SLURM_CPUS_PER_TASK}}"
CMD="${{CMD//@NODEDIR@/$NODE_DIR}}"

# Disk monitor: node-file usage (peak) and free space of the node-file disk every 60 s, warning below {disk_min_free_gb} GB free
(
  peak=0; minfree=-1
  while sleep 60; do
    used=$(du -sm "$NODE_DIR" 2>/dev/null | cut -f1) || used=0
    free=$(df -Pm "$NODE_DIR" 2>/dev/null | awk 'NR == 2 {{print $4}}') || free=-1
    [ "${{used:-0}}" -gt "$peak" ] && peak=${{used:-0}}
    if [ "${{free:--1}}" -ge 0 ] && {{ [ "$minfree" -lt 0 ] || [ "$free" -lt "$minfree" ]; }}; then minfree=$free; fi
    echo "$peak $minfree" > "$NODE_DIR.usage"
    if [ "${{free:--1}}" -ge 0 ] && [ "$free" -lt $(( {disk_min_free_gb} * 1024 )) ]; then
      echo "WARNING $(date +%FT%T): only $free MB free on the node-file disk ($NODE_DIR holds $used MB)"
    fi
  done
) &
MONITOR_PID=$!
trap 'kill $MONITOR_PID 2>/dev/null; if [ -f "$NODE_DIR.usage" ]; then read -r p f < "$NODE_DIR.usage"; echo "Node files: peak $p MB, min free disk $f MB"; fi; rm -rf "$NODE_DIR" "$NODE_DIR.usage"' EXIT

echo "=========================================================="
echo "Task: $KEY"
echo "Slurm job: $SLURM_JOB_ID (array $SLURM_ARRAY_JOB_ID, index $IDX) on $SLURM_JOB_NODELIST"
echo "Cores: $SLURM_CPUS_PER_TASK, memory: $SLURM_MEM_PER_NODE MB"
echo "Command: $CMD"
echo "=========================================================="

{setup}

cd "{repo}"
# srun does not inherit --cpus-per-task from sbatch (Slurm >= 22.05); without this the solve runs on one core
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"
read -ra ARGS <<< "$CMD"
srun "${{ARGS[@]}}"
"""


########################################################################################################################
# Plan: config -> tasks
########################################################################################################################

def _tm_variant(spec: str) -> tuple[str, list[str]]:
    """'base' | 'shift:N' | 'perturb:R' -> (label used in task keys, Markov.py arguments)."""
    if spec == "base":
        return "base", []
    kind, _, value = spec.partition(":")
    if kind == "shift":
        return f"shiftTM{int(value)}", ["--shift-tm", str(int(value))]
    if kind == "perturb":
        return f"perturbTM{float(value):g}", ["--perturb-tm", value]
    raise ValueError(f"Unknown tm variant '{spec}' (use 'base', 'shift:N' or 'perturb:R')")


def _tm_entry(entry) -> tuple[str, list[str], set[float] | None, bool]:
    """grid.tm entry: 'spec' or {spec, stretch_demand = [...] (only these demand levels), low_priority = bool}
    -> (label, Markov.py arguments, allowed stretch_demand values or None = all, low priority)."""
    if isinstance(entry, str):
        return *_tm_variant(entry), None, False
    unknown = set(entry) - {"spec", "stretch_demand", "low_priority"}
    if unknown or "spec" not in entry:
        raise ValueError(f"grid.tm entry {entry}: needs 'spec', optional 'stretch_demand' and 'low_priority' (unknown: {sorted(unknown)})")
    sds = {float(s) for s in entry["stretch_demand"]} if "stretch_demand" in entry else None
    return *_tm_variant(entry["spec"]), sds, bool(entry.get("low_priority", False))


def _resources(cfg: dict, res_class: str, dataset: str) -> dict:
    """[resources.<class>] default, overridden by its <dataset> entry; truth-original falls back to the 'full' class."""
    res_cfg = cfg["resources"]
    if res_class not in res_cfg and res_class == "truth-original":
        res_class = "full"
    section = res_cfg[res_class]
    flat = {k: v for k, v in section.items() if not isinstance(v, dict)}
    res = {**section.get("default", {}), **flat, **section.get(dataset, {})}
    missing = {"cpus", "mem", "time"} - res.keys()
    if missing:
        raise ValueError(f"[resources.{res_class}] for '{dataset}' lacks {sorted(missing)}")
    return {"cpus": int(res["cpus"]), "mem": str(res["mem"]), "time": str(res["time"])}


def _node_file_start(markov: dict, dataset: str) -> float | None:
    """[markov] node_file_start (GB): a number for all datasets, or a table {default = .., "<dataset>" = ..}; None = off."""
    value = markov.get("node_file_start")
    if isinstance(value, dict):
        value = value.get(dataset, value.get("default"))
    if value is None:
        return None
    if float(value) <= 0:
        raise ValueError(f"[markov] node_file_start for '{dataset}' must be > 0 (GB)")
    return float(value)


def _dataset_codes(datasets: list[str]) -> dict:
    """{dataset folder name: 2-character job-name code} (first two letters/digits, upper case), unique per run."""
    codes = {}
    for dataset in datasets:
        name = Path(dataset).name
        codes[name] = re.sub(r"[^A-Za-z0-9]", "", name)[:2].upper().ljust(2, "X")
    clashes = {c for c in codes.values() if list(codes.values()).count(c) > 1}
    if clashes:
        raise ValueError(f"grid.datasets: job-name codes {sorted(clashes)} are not unique ({codes}) - rename a dataset folder "
                         f"or extend _dataset_codes")
    return codes


def build_plan(cfg: dict) -> dict:
    """All tasks of the config: {key: {key, group, index, cmd, res, deps}}. Tasks of one group (= one job array) share
    task kind, edge handling and dataset (hence resources); within a dataset every grid point has the same index in
    all its groups, so array dependencies can use aftercorr (task i waits for task i)."""
    grid, markov = cfg["grid"], cfg.get("markov", {})
    tasks = sorted(grid["tasks"], key=GRID_TASKS.index)
    for task in tasks:
        for dep_task, _ in TASK_DEPS[task]:
            if dep_task not in tasks:
                raise ValueError(f"grid.tasks: '{task}' needs '{dep_task}'")
    edges = grid["edges"]
    tms = [_tm_entry(t) for t in grid["tm"]]
    stretch = [float(s) for s in grid.get("stretch_demand", [1.0])]
    for label, _, sds, _ in tms:
        if sds is not None and not sds <= set(stretch):
            raise ValueError(f"grid.tm '{label}': stretch_demand {sorted(sds - set(stretch))} not in grid.stretch_demand")
    clusters = [int(c) for c in grid["clusters"]]

    if "node_file_start_fraction" in markov:
        raise ValueError("[markov] node_file_start_fraction was replaced by an absolute node_file_start (GB), e.g. "
                         "node_file_start = { default = 8, \"TX-123BT\" = 16 }: NodefileStart affects the runtime, so it must "
                         "not depend on a job's memory request")

    def solver_args(name):
        """--threads plus, if configured, the dataset's absolute NodefileStart (same for all its solves)."""
        nfs = _node_file_start(markov, name)
        return ["--threads", "@THREADS@"] + (["--node-file-start", f"{nfs:g}", "--node-file-dir", "@NODEDIR@"] if nfs is not None else [])

    def markov_cmd(dataset, sd, *extra):
        cmd = ["python", "research/MK/Markov.py", dataset, "--reuse-inputfiles", "--no-overwrite", "--debug", *markov.get("args", [])]
        if sd != 1.0:
            cmd += ["--stretch-demand", f"{sd:g}"]
        return cmd + list(extra)

    plan = {}
    ds_codes = _dataset_codes(grid["datasets"])
    rank = {name: i for i, name in enumerate(ds_codes)}  # scheduling preference among the own jobs = grid.datasets order

    def add(key, group, index, cmd, res, deps, dataset=None, task=None, edge=None, low=False):
        bad = [a for a in cmd if re.search(r"[\s'\"\\]", a)]
        if bad:
            raise ValueError(f"Arguments must not contain whitespace or quotes (the job script splits on whitespace): {bad}")
        # Low-priority tasks: lower-case dataset code (tells their arrays apart in squeue), ranked after all datasets
        code = ds_codes.get(dataset, "")
        jobname = group if dataset is None else f"{code.lower() if low else code}{TASK_CODES[task]}{EDGE_CODES.get(edge, edge and edge[:2])}_{group}"
        task_rank = rank.get(dataset, 0) + (len(rank) if low else 0)  # evaluate (no dataset): 0
        plan[key] = {"key": key, "group": group, "jobname": jobname, "rank": task_rank, "dataset_rank": rank.get(dataset, 0), "low": low, "index": index, "cmd": " ".join(cmd), "res": res, "deps": deps}

    for dataset in grid["datasets"]:
        name = Path(dataset).name
        for si, sd in enumerate(stretch, 1):
            prefix = f"{name}/sd{sd:g}"
            add(f"{prefix}/prepare", f"prepare-{name}", si,
                markov_cmd(dataset, sd, "--clusters", ",".join(map(str, clusters)), "--prepare-only"),
                _resources(cfg, "prepare", name), [], name, "prepare")
            if grid.get("truth_original", False):
                add(f"{prefix}/truth-original", f"truth-original-{name}", si, markov_cmd(dataset, sd, *solver_args(name), "--task", "truth-original"),
                    _resources(cfg, "truth-original", name), [f"{prefix}/prepare"], name, "truth-original")

        # Grid points longest first: high cluster counts, then the TM variants in config order (base first). Low-priority
        # TM variants form their own job arrays (one --nice per array) with their own index sequence.
        points = sorted(((si, c, ti) for si, c, ti in itertools.product(range(len(stretch)), clusters, range(len(tms)))
                         if tms[ti][2] is None or stretch[si] in tms[ti][2]), key=lambda p: (-p[1], p[2], p[0]))
        for low in (False, True):
            for gi, (si, c, ti) in enumerate([p for p in points if tms[p[2]][3] == low], 1):
                sd, (tm_label, tm_args, _, _) = stretch[si], tms[ti]
                prefix = f"{name}/sd{sd:g}/c{c}/{tm_label}"
                for task in tasks:
                    if task in ORIGINAL_TASKS and tm_label != "base":
                        continue
                    for edge in (["Truth"] if task in TRUTH_TASKS else []) + edges:
                        deps = [f"{prefix}/{t}/{edge if e == 'EDGE' else e}" for t, e in TASK_DEPS[task]] or [f"{name}/sd{sd:g}/prepare"]
                        key = f"{prefix}/{task}/{edge}"
                        add(key, f"{task}-{edge}-{name}" + ("-low" if low else ""), gi,
                            markov_cmd(dataset, sd, *solver_args(name), "--clusters", str(c), *tm_args, "--task", task, "--edge", edge),
                            _resources(cfg, resource_class(key), name), deps, name, task, edge, low)

    # Work units / solver times are compared between edge handlings and Truth: all solves of a dataset need the same threads
    for dataset in grid["datasets"]:
        name = Path(dataset).name
        solves = [t for t in plan.values() if t["key"].startswith(f"{name}/") and not t["key"].endswith("/prepare")]
        cpus = {t["res"]["cpus"] for t in solves}
        if len(cpus) > 1:
            raise ValueError(f"[resources]: the solves of '{name}' use different cpus {sorted(cpus)} - set the same cpus for rp, full "
                             f"and truth-original, otherwise work units and solver times are not comparable")

    evaluate = cfg.get("evaluate")
    if evaluate is not None:
        cmd = ["python", "research/MK/EvaluateMarkov.py", *evaluate.get("args", ["all", "--no-show"])]
        if evaluate.get("output_dir"):
            cmd += ["--output-dir", evaluate["output_dir"]]
        add("evaluate", "evaluate", 1, cmd, _resources(cfg, "evaluate", "evaluate"), [])

    # squeue shows 8 characters of the job name: they must tell the job arrays apart
    heads = {}
    for t in plan.values():
        heads.setdefault(t["jobname"][:8], set()).add(t["group"])
    clashes = {h: sorted(g) for h, g in heads.items() if len(g) > 1}
    if clashes:
        raise ValueError(f"Job names not distinguishable by their first 8 characters: {clashes} - extend TASK_CODES/EDGE_CODES")
    return plan


def group_tasks(plan: dict) -> dict:
    """{group: [task, ...]} in plan (= dependency) order."""
    groups = {}
    for task in plan.values():
        groups.setdefault(task["group"], []).append(task)
    return groups


def group_dependency(plan: dict, members: list) -> str | None:
    """Slurm --dependency of a job array: aftercorr on parent groups whose task i the task i depends on, afterok on
    whole parent groups otherwise (prepare). Parent groups are referenced as '@group' and resolved at submission."""
    same_index = {}  # parent group -> every dependency into it has the dependent task's own index
    for task in members:
        for dep in task["deps"]:
            parent = plan[dep]
            same_index[parent["group"]] = same_index.get(parent["group"], True) and parent["index"] == task["index"]
    corr = [g for g, same in same_index.items() if same]
    whole = [g for g, same in same_index.items() if not same]
    parts = ([f"aftercorr:{':'.join('@' + g for g in corr)}"] if corr else []) + ([f"afterok:{':'.join('@' + g for g in whole)}"] if whole else [])
    return ",".join(parts) or None


def compress_indices(indices: list[int]) -> str:
    """[1, 2, 3, 7] -> '1-3,7'."""
    out = []
    for _, run in itertools.groupby(enumerate(sorted(indices)), lambda p: p[1] - p[0]):
        run = [i for _, i in run]
        out.append(f"{run[0]}-{run[-1]}" if len(run) > 1 else str(run[0]))
    return ",".join(out)


########################################################################################################################
# Slurm interaction
########################################################################################################################

class Slurm:
    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self._dry_id = 0

    def sbatch(self, args: list[str]) -> str:
        cmd = ["sbatch", "--parsable", *args]
        if self.dry_run:
            self._dry_id += 1
            print("  " + " ".join(cmd))
            return f"DRY{self._dry_id}"
        out = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout.strip()
        return out.split(";")[0]

    def scancel(self, job_ids: list[str]) -> None:
        if not job_ids:
            return
        if self.dry_run:
            print("  scancel " + " ".join(job_ids))
            return
        for i in range(0, len(job_ids), 200):
            subprocess.run(["scancel", *job_ids[i:i + 200]], check=False)

    def renice(self, nice_jobs: dict[int, list[str]]) -> None:
        """scontrol update Nice of queued jobs, {nice: [job id, ...]} (an array id covers the array's pending tasks)."""
        for nice, job_ids in nice_jobs.items():
            for i in range(0, len(job_ids), 200):
                cmd = ["scontrol", "update", f"JobId={','.join(job_ids[i:i + 200])}", f"Nice={nice}"]
                if self.dry_run:
                    print("  " + " ".join(cmd))
                    continue
                out = subprocess.run(cmd, capture_output=True, text=True)
                if out.returncode != 0:
                    print(f"  warning: setting Nice={nice} failed ({(out.stderr or out.stdout).strip()})")

    @staticmethod
    def query(job_ids: set[str]) -> dict:
        """{job id ('A_i' or 'J'): {state, reason, exit, elapsed, maxrss_mb, reqmem}} from squeue (queued/running,
        array tasks expanded) and sacct (everything that started)."""
        info = {}
        parents = sorted({j.split("_")[0] for j in job_ids if not j.startswith("DRY")})
        if not parents:
            return info
        for i in range(0, len(parents), 200):
            out = subprocess.run(["sacct", "-n", "-P", "-j", ",".join(parents[i:i + 200]),
                                  "--format=JobID,State,ExitCode,Elapsed,MaxRSS,ReqMem"], capture_output=True, text=True).stdout
            for line in out.splitlines():
                job, state, exit_code, elapsed, maxrss, reqmem = (line.split("|") + [""] * 6)[:6]
                if "[" in job:
                    continue  # still-pending part of an array: squeue has the expanded tasks
                base, _, step = job.partition(".")
                entry = info.setdefault(base, {})
                if step:
                    rss = _mem_mb(maxrss)
                    if rss is not None:
                        entry["maxrss_mb"] = max(entry.get("maxrss_mb", 0), rss)
                else:
                    entry.update(state=state.split()[0], exit=exit_code, elapsed=elapsed, reqmem=reqmem)
        user = os.environ.get("USER", "")
        out = subprocess.run(["squeue", "-h", "-r", "-u", user, "-o", "%i|%T|%r"], capture_output=True, text=True).stdout
        for line in out.splitlines():
            job, state, reason = (line.split("|") + ["", ""])[:3]
            if job.split("_")[0] in parents:
                info.setdefault(job, {}).update(state=state, reason=reason)
        return info


def _mem_mb(value: str) -> float | None:
    m = re.fullmatch(r"([\d.]+)([KMGT]?)n?c?", value.strip())
    if not m:
        return None
    return float(m.group(1)) * {"": 1 / 1024 ** 2, "K": 1 / 1024, "M": 1, "G": 1024, "T": 1024 ** 2}[m.group(2)]


def _fmt_mem(mb: float) -> str:
    return f"{mb / 1024:.0f}G" if mb >= 10 * 1024 else f"{mb:.0f}M"


def _scale_mem(mem: str, factor: float) -> str:
    return _fmt_mem(_mem_mb(mem.upper().removesuffix("B")) * factor)


########################################################################################################################
# Run state
########################################################################################################################

def run_dir(name_or_config: str) -> Path:
    path = Path(name_or_config)
    name = tomllib.loads(path.read_text())["name"] if path.is_file() else name_or_config
    return RUNS_DIR / name


def load_state(name_or_config: str) -> tuple[Path, dict]:
    rdir = run_dir(name_or_config)
    if not (rdir / "state.json").exists():
        sys.exit(f"No submitted run in '{rdir}' (submit it first)")
    return rdir, json.loads((rdir / "state.json").read_text())


def save_state(rdir: Path, state: dict) -> None:
    tmp = rdir / "state.json.tmp"
    tmp.write_text(json.dumps(state, indent=1))
    tmp.replace(rdir / "state.json")


def _now() -> str:
    return datetime.datetime.now().isoformat(timespec="seconds")


def current_job(task: dict) -> str | None:
    return task["attempts"][-1]["job"] if task["attempts"] else None


def nice(task: dict, step: int) -> int:
    """sbatch --nice of a task: rank (grid.datasets order, low-priority TM variants after all datasets) x nice_step. A positive
    nice is the only way to order the own jobs without operator rights; it costs the same against other users' jobs."""
    return task.get("rank", 0) * step


def _nice_step(value) -> int:
    step = int(value)
    if step < 0:
        sys.exit("nice_step must be >= 0 (a negative nice needs operator rights)")
    return step


def prioritize(state: dict, keys, slurm: "Slurm") -> None:
    """Re-apply the nice of the given (queued) tasks' jobs, e.g. after changing nice_step. Array jobs go in by array id."""
    nice_jobs = {}
    for key in keys:
        job = current_job(state["tasks"][key])
        job = job and job.split("_")[0]
        jobs = nice_jobs.setdefault(nice(state["tasks"][key], state.get("nice_step", DEFAULT_NICE_STEP)), [])
        if job and job not in jobs:
            jobs.append(job)
    if not nice_jobs:
        print("No queued jobs")
        return
    print(f"Setting the nice of {sum(map(len, nice_jobs.values()))} queued job(s) / array(s): "
          + ", ".join(f"{len(j)} x {n}" for n, j in sorted(nice_jobs.items())))
    slurm.renice(nice_jobs)


def classify(state: dict, info: dict) -> dict:
    """{key: (category, slurm info)}. A task whose job is pending on a dependency that can never be satisfied, or that
    was cancelled while an ancestor failed, counts as blocked."""
    result = {}
    for key, task in state["tasks"].items():
        job = current_job(task)
        entry = info.get(job, {}) if job else {}
        st = entry.get("state", "")
        if st == "COMPLETED":
            cat = DONE
        elif st in _RUNNING_STATES:
            cat = RUNNING
        elif st == "PENDING":
            cat = BLOCKED if "DependencyNeverSatisfied" in entry.get("reason", "") else PENDING
        elif st in _FAILED_STATES:
            cat = FAILED
        else:
            cat = UNKNOWN
        result[key] = [cat, entry]
    for key in state["tasks"]:  # cancelled because of a failed ancestor -> blocked (kill_invalid_depend clusters)
        if result[key][0] == FAILED and result[key][1].get("state") == "CANCELLED" and failed_ancestors(state, result, key):
            result[key][0] = BLOCKED
    return result


def failed_ancestors(state: dict, status: dict, key: str) -> list[str]:
    found, stack, seen = [], list(state["tasks"][key]["deps"]), set()
    while stack:
        dep = stack.pop()
        if dep in seen:
            continue
        seen.add(dep)
        if status[dep][0] == FAILED and status[dep][1].get("state") != "CANCELLED":
            found.append(dep)
        else:
            stack.extend(state["tasks"][dep]["deps"])
    return found


def descendants(state: dict, keys: set[str]) -> list[str]:
    """All tasks depending (transitively) on keys, in plan order (excluding keys and evaluate)."""
    children = {}
    for key, task in state["tasks"].items():
        for dep in task["deps"]:
            children.setdefault(dep, []).append(key)
    found, stack = set(), list(keys)
    while stack:
        for child in children.get(stack.pop(), []):
            if child not in found and child not in keys:
                found.add(child)
                stack.append(child)
    return [k for k in state["tasks"] if k in found]


########################################################################################################################
# Commands
########################################################################################################################

def cmd_submit(args) -> None:
    cfg = tomllib.loads(Path(args.config).read_text())
    rdir = RUNS_DIR / cfg["name"]
    if (rdir / "state.json").exists() and not args.dry_run:
        sys.exit(f"'{rdir}' already holds a submitted run - use status/restart, or delete the folder to start over")
    plan = build_plan(cfg)
    groups = group_tasks(plan)
    # NodefileStart limits only the B&B tree: at or above a job's memory limit it can never prevent an OOM of that job
    for dataset in cfg["grid"]["datasets"]:
        name = Path(dataset).name
        nfs = _node_file_start(cfg.get("markov", {}), name)
        mems = sorted({t["res"]["mem"] for t in plan.values() if t["key"].startswith(f"{name}/") and resource_class(t["key"]) != "prepare"
                       and nfs is not None and _mem_mb(t["res"]["mem"].upper().removesuffix("B")) <= nfs * 1024})
        if mems:
            print(f"warning: node_file_start of '{name}' ({nfs:g} GB) is not below the Slurm memory {mems} of some of its solves - "
                  f"node files cannot protect those jobs from running out of memory")

    slurm_cfg = cfg["slurm"]
    nice_step = _nice_step(slurm_cfg.get("nice_step", DEFAULT_NICE_STEP))
    # Mail address from the config or $MK_MAIL_USER (keeps it out of the repo); without one, no mails are requested
    mail_user = slurm_cfg.get("mail_user") or os.environ.get("MK_MAIL_USER", "")
    mail = f"#SBATCH --mail-type={slurm_cfg.get('mail_type', 'FAIL')}\n#SBATCH --mail-user={mail_user}\n" if mail_user else ""
    disk_min_free_gb = int(slurm_cfg.get("disk_min_free_gb", DEFAULT_DISK_MIN_FREE_GB))  # integer: bash arithmetic
    script = SBATCH_TEMPLATE.format(disk_min_free_gb=disk_min_free_gb, account=slurm_cfg["account"], partition=slurm_cfg["partition"], qos=slurm_cfg.get("qos", slurm_cfg["partition"]), mail=mail,
                                    setup=slurm_cfg.get("setup", "").strip(), repo=slurm_cfg["repo"])
    out_dir = rdir if not args.dry_run else rdir.with_name(rdir.name + "-dryrun")
    (out_dir / "logs").mkdir(parents=True, exist_ok=True)
    (out_dir / "commands").mkdir(exist_ok=True)
    (out_dir / "task.sbatch").write_text(script, newline="\n")
    if cfg.get("evaluate", {}).get("output_dir"):
        Path(cfg["evaluate"]["output_dir"]).mkdir(parents=True, exist_ok=True)

    state = {"config": str(Path(args.config).resolve()), "created": _now(), "rundir": str(out_dir.resolve()),
             "mail": bool(mail_user), "nice_step": nice_step, "tasks": {k: {**t, "attempts": []} for k, t in plan.items()}, "groups": {}}
    slurm = Slurm(dry_run=args.dry_run)
    print(f"{len(plan)} tasks in {len(groups)} job arrays")
    for group, members in groups.items():
        cmd_file = out_dir / "commands" / f"{group}.tsv"
        cmd_file.write_text("".join(f"{t['index']}\t{t['key']}\t{t['cmd']}\n" for t in members), newline="\n")
        res = members[0]["res"]
        if group == "evaluate":
            dependency = "afterany:" + ":".join(g["job"] for g in state["groups"].values())
            sbatch_args = ["--export=ALL,TASK_INDEX=1", f"--output={out_dir / 'logs' / 'evaluate_%j.out'}", *(["--mail-type=END,FAIL"] if mail_user else [])]
        else:
            dependency = group_dependency(plan, members)
            if dependency:
                dependency = re.sub(r"@([^:,]+)", lambda m: state["groups"][m.group(1)]["job"], dependency)
            sbatch_args = [f"--array={compress_indices([t['index'] for t in members])}", f"--output={out_dir / 'logs' / (group + '_%A_%a.out')}"]
        job = slurm.sbatch([f"--job-name={members[0]['jobname']}", f"--cpus-per-task={res['cpus']}", f"--mem={res['mem']}",
                            f"--time={res['time']}", f"--nice={nice(members[0], nice_step)}", *sbatch_args, *([f"--dependency={dependency}"] if dependency else []), str(out_dir / "task.sbatch"), str(cmd_file)])
        state["groups"][group] = {"job": job, "cmdfile": str(cmd_file)}
        for t in members:
            task_job, log = (job, out_dir / "logs" / f"evaluate_{job}.out") if group == "evaluate" else \
                (f"{job}_{t['index']}", out_dir / "logs" / f"{group}_{job}_{t['index']}.out")
            state["tasks"][t["key"]]["attempts"].append({"job": task_job, "log": str(log), "res": res, "time": _now()})
        save_state(out_dir, state)  # after every array, so a failed submission can be inspected / cancelled
    print(f"State: {out_dir / 'state.json'}" + ("  (dry run: nothing submitted)" if args.dry_run else ""))


def cmd_status(args) -> None:
    pool_run = load_pool(args.run)
    if pool_run:
        return cmd_pool_status(args, pool_run[0], pool_run[1], pool_run[3])
    rdir, state = load_state(args.run)
    status = classify(state, Slurm.query({current_job(t) for t in state["tasks"].values() if current_job(t)}))

    def kind(key):
        return "/".join(key.split("/")[-2:]) if "/c" in key else key.split("/")[-1]  # e.g. 'regret/Markov', 'prepare'

    counts = {}
    for key, (cat, _) in status.items():
        counts.setdefault(kind(key), dict.fromkeys(CATEGORIES, 0))[cat] += 1
    width = max(len(k) for k in counts)
    print(f"{'task':<{width}}  {'total':>6}" + "".join(f"  {c:>8}" for c in CATEGORIES))
    for k, row in counts.items():
        print(f"{k:<{width}}  {sum(row.values()):>6}" + "".join(f"  {row[c] or '':>8}" for c in CATEGORIES))
    totals = {c: sum(r[c] for r in counts.values()) for c in CATEGORIES}
    print(f"{'TOTAL':<{width}}  {len(status):>6}" + "".join(f"  {totals[c]:>8}" for c in CATEGORIES))

    def line(key, entry):
        task = state["tasks"][key]
        rss = entry.get("maxrss_mb")
        mem = f"mem {_fmt_mem(rss)}/{task['attempts'][-1]['res']['mem']}" if rss else ""
        return (f"  {key:<55} {entry.get('state', '?'):<14} exit {entry.get('exit', '-'):<6} {entry.get('elapsed', ''):>11} {mem:<16}"
                f" job {current_job(task)}  (attempt {len(task['attempts'])})\n      log: {task['attempts'][-1]['log']}")

    shown = [args.list] if args.list else [FAILED, BLOCKED, UNKNOWN]
    for cat in shown:
        keys = [k for k, (c, _) in status.items() if c == cat and (args.filter is None or fnmatch.fnmatch(k, args.filter))]
        if not keys:
            continue
        print(f"\n{cat.upper()} ({len(keys)})")
        if cat == BLOCKED and not args.list:  # group by the failed task they wait for
            by_root = {}
            for k in keys:
                for root in failed_ancestors(state, status, k) or ["(unknown)"]:
                    by_root.setdefault(root, []).append(k)
            for root, ks in by_root.items():
                print(f"  {len(ks):>4} task(s) waiting for {root}")
        else:
            for k in keys:
                print(line(k, status[k][1]))
    if not args.list:
        print("\nRestart failed tasks (and the tasks waiting for them): cluster.py restart <run> --failed [--mem-factor 1.5]")


def cmd_restart(args) -> None:
    pool_run = load_pool(args.run)
    if pool_run:
        return cmd_pool_restart(args, pool_run[1], pool_run[3])
    rdir, state = load_state(args.run)
    tasks = state["tasks"]
    status = classify(state, Slurm.query({current_job(t) for t in tasks.values() if current_job(t)}))
    restartable = {FAILED, BLOCKED, UNKNOWN} | ({PENDING} if args.include_pending else set())

    selected = [k for k in tasks if k != "evaluate" and status[k][0] in restartable and
                ((args.failed and status[k][0] == FAILED) or any(fnmatch.fnmatch(k, p) for p in args.patterns))]
    skipped = [k for k in tasks if any(fnmatch.fnmatch(k, p) for p in args.patterns) and k not in selected and k != "evaluate"]
    if skipped:
        print(f"Not restarting {len(skipped)} matching task(s) that are {sorted({status[k][0] for k in skipped})} "
              f"(done runs are skipped by --no-overwrite anyway; delete the .sqlite to recompute; queued ones need --include-pending)")
    if not selected:
        sys.exit("Nothing to restart")
    # Everything downstream that has not finished must be resubmitted too: its old jobs wait for the old (failed) ones
    follow = [k for k in descendants(state, set(selected)) if status[k][0] in {PENDING, BLOCKED, FAILED, UNKNOWN}]
    resubmit = [k for k in tasks if k in set(selected) | set(follow)]  # plan order = dependency order
    print(f"Restarting {len(selected)} task(s) + {len(follow)} dependent task(s)")
    if args.cpus:
        print(f"  warning: --cpus {args.cpus} makes the work units / solver times of the restarted tasks incomparable to the other "
              f"solves of their dataset (prefer --mem / --time)")

    slurm = Slurm(dry_run=args.dry_run)
    nice_step = state.get("nice_step", DEFAULT_NICE_STEP)
    slurm.scancel([current_job(tasks[k]) for k in resubmit if status[k][0] in {PENDING, BLOCKED}])
    new_jobs = {}
    for key in resubmit:
        task = tasks[key]
        res = dict(task["attempts"][-1]["res"])
        if key in selected:
            if args.mem:
                res["mem"] = args.mem
            elif args.mem_factor:
                res["mem"] = _scale_mem(res["mem"], args.mem_factor)
            if args.cpus:
                res["cpus"] = args.cpus
            if args.time:
                res["time"] = args.time
        deps = []
        for dep in task["deps"]:
            if dep in new_jobs:
                deps.append(new_jobs[dep])
            elif status[dep][0] != DONE:
                if status[dep][0] not in {RUNNING, PENDING}:
                    print(f"  warning: {key} depends on {dep} ({status[dep][0]}), which is not restarted - it will not start")
                deps.append(current_job(tasks[dep]))
        group = task["group"]
        job = slurm.sbatch([f"--job-name={task.get('jobname', group)}", f"--cpus-per-task={res['cpus']}", f"--mem={res['mem']}",
                            f"--time={res['time']}", f"--nice={nice(task, nice_step)}", f"--export=ALL,TASK_INDEX={task['index']}", f"--output={Path(state['rundir']) / 'logs' / (group + '_%j.out')}",
                            *([f"--dependency=afterok:{':'.join(deps)}"] if deps else []),
                            str(Path(state["rundir"]) / "task.sbatch"), state["groups"][group]["cmdfile"]])
        new_jobs[key] = job
        task["attempts"].append({"job": job, "log": str(Path(state["rundir"]) / "logs" / f"{group}_{job}.out"), "res": res, "time": _now()})

    # Evaluation must wait for the new jobs too
    if "evaluate" in tasks and status["evaluate"][0] not in {DONE, RUNNING}:
        if status["evaluate"][0] in {PENDING, BLOCKED}:
            slurm.scancel([current_job(tasks["evaluate"])])
        active = [current_job(t) for k, t in tasks.items() if k != "evaluate" and (k in new_jobs or status[k][0] in {PENDING, RUNNING})]
        active = sorted({j.split("_")[0] if "_" in j else j for j in active})
        ev = tasks["evaluate"]
        res = ev["attempts"][-1]["res"]
        job = slurm.sbatch(["--job-name=evaluate", f"--cpus-per-task={res['cpus']}", f"--mem={res['mem']}", f"--time={res['time']}",
                            "--export=ALL,TASK_INDEX=1", f"--output={Path(state['rundir']) / 'logs' / 'evaluate_%j.out'}", *(["--mail-type=END,FAIL"] if state.get("mail", True) else []),
                            *([f"--dependency=afterany:{':'.join(active)}"] if active else []),
                            str(Path(state["rundir"]) / "task.sbatch"), state["groups"]["evaluate"]["cmdfile"]])
        ev["attempts"].append({"job": job, "log": str(Path(state["rundir"]) / "logs" / f"evaluate_{job}.out"), "res": res, "time": _now()})
    if not args.dry_run:
        save_state(rdir, state)


def _elapsed_s(value: str) -> int | None:
    """Slurm elapsed '[D-]HH:MM:SS' / 'MM:SS' -> seconds."""
    m = re.fullmatch(r"(?:(\d+)-)?(?:(\d+):)?(\d+):(\d+)", value.strip())
    if not m:
        return None
    d, h, mi, s = (int(x) if x else 0 for x in m.groups())
    return ((d * 24 + h) * 60 + mi) * 60 + s


def _fmt_time(seconds: float) -> str:
    """Seconds -> Slurm time '[D-]HH:MM:SS'."""
    seconds = int(seconds)
    d, rest = divmod(seconds, 86400)
    return (f"{d}-" if d else "") + f"{rest // 3600:02d}:{rest % 3600 // 60:02d}:{rest % 60:02d}"


def resource_class(key: str) -> str:
    """[resources.*] class of a task key (same rule as build_plan)."""
    parts = key.split("/")
    if key == "evaluate" or parts[-1] in ("prepare", "truth-original"):
        return parts[-1]
    task, edge = parts[-2], parts[-1]
    return "rp" if task in ("main", "operational") and edge != "Truth" else "full"


def cmd_resources(args) -> None:
    """Measured peak memory / runtime per (dataset, resource class) and suggested [resources.*] values. Slurm runs: from
    sacct (`--save` writes runs/<run>/measurements.json, which pool runs use as seed); pool runs: from the pool results."""
    groups = {}  # (dataset, class) -> {"done": [(key, rss_mb, elapsed_s, requested)], "limit": [(key, what, limit)], "open": n}

    def group(key):
        dataset = key.split("/")[0] if key != "evaluate" else "evaluate"
        return groups.setdefault((dataset, resource_class(key)), {"done": [], "limit": [], "open": 0})

    pool_run = load_pool(args.run)
    if pool_run:
        rdir, store, _, plan = pool_run
        status = pool_status(plan, store)
        for record in store.results():
            est = record.get("estimate") or {}
            requested = {"mem": _fmt_mem(est["mem_mb"]) if est.get("mem_mb") else "?", "time": _fmt_time(est["time_s"]) if est.get("time_s") else "?"}
            if record["key"] not in plan:
                continue
            if record["outcome"] == pool.DONE and record.get("noop"):
                continue  # had nothing to do (output existed): no measurement
            if record["outcome"] == pool.DONE:
                group(record["key"])["done"].append((record["key"], record.get("peak_rss_mb"), record.get("elapsed_s"), requested))
            elif record["outcome"] == pool.EVICTED:
                group(record["key"])["limit"].append((record["key"], "evicted", _fmt_mem(record.get("peak_rss_mb") or 0)))
            elif record["outcome"] == pool.INTERRUPTED:
                group(record["key"])["limit"].append((record["key"], "interrupted", _fmt_time(record.get("elapsed_s") or 0)))
        for key, (cat, _) in status.items():
            if cat in (PENDING, RUNNING, BLOCKED):
                group(key)["open"] += 1
        print("Source: pool results ('requested' = the estimate the attempt started with; evicted = memory ran out, "
              "interrupted = walltime ended)")
    else:
        rdir, state = load_state(args.run)
        status = classify(state, Slurm.query({current_job(t) for t in state["tasks"].values() if current_job(t)}))
        measurements = []
        for key, (cat, entry) in status.items():
            res = state["tasks"][key]["attempts"][-1]["res"]
            rss, elapsed = entry.get("maxrss_mb"), _elapsed_s(entry.get("elapsed", ""))
            if cat == DONE and pool._log_has_marker(Path(state["tasks"][key]["attempts"][-1]["log"]), pool.NOOP_MARKER):
                continue  # had nothing to do (output existed): no measurement
            if cat == DONE:
                group(key)["done"].append((key, rss, elapsed, res))
                measurements.append({"key": key, "outcome": pool.DONE, "peak_rss_mb": rss, "elapsed_s": elapsed, "job": current_job(state["tasks"][key])})
            elif cat == FAILED and entry.get("state") in ("OUT_OF_MEMORY", "TIMEOUT"):
                oom = entry["state"] == "OUT_OF_MEMORY"  # hit a limit: the true need is above the request
                group(key)["limit"].append((key, entry["state"], res["mem"] if oom else res["time"]))
                measurements.append({"key": key, "outcome": "oom" if oom else "timeout", "peak_rss_mb": rss, "elapsed_s": elapsed,
                                     "limit_mb": _mem_mb(res["mem"].upper().removesuffix("B")), "limit_s": _elapsed_s(res["time"]),
                                     "job": current_job(state["tasks"][key])})
            elif cat in (PENDING, RUNNING, BLOCKED, UNKNOWN):
                group(key)["open"] += 1
        if args.save:
            (rdir / "measurements.json").write_text(json.dumps(measurements, indent=1))
            print(f"Saved {len(measurements)} measurement(s) to {rdir / 'measurements.json'} (seed for pool runs: [pool] seed_runs)\n")

    print(f"Suggestions: mem = {args.mem_factor:g} x max peak, time = {args.time_factor:g} x max elapsed "
          f"(min {_fmt_time(args.min_time * 60)}); based on finished tasks only\n")
    head = f"{'dataset':<10} {'class':<15} {'done':>4} {'open':>4}  {'max peak':>9} {'requested':>9} {'-> mem':>7}   {'max elapsed':>11} {'requested':>11} {'-> time':>11}  peak / longest task"
    print(head)
    print("-" * len(head))
    for (dataset, cls), g in sorted(groups.items(), key=lambda x: (x[0][0] == "evaluate", x[0][0], x[0][1])):
        done = g["done"]
        if not done:
            print(f"{dataset:<10} {cls:<15} {0:>4} {g['open']:>4}  (nothing finished yet)")
        else:
            with_rss = [d for d in done if d[1] is not None]
            with_time = [d for d in done if d[2] is not None]
            peak = max(with_rss, key=lambda d: d[1]) if with_rss else None
            longest = max(with_time, key=lambda d: d[2]) if with_time else None
            mem_s = f"{_fmt_mem(peak[1]):>9} {peak[3]['mem']:>9} {_fmt_mem(max(peak[1] * args.mem_factor, 1024)):>7}" if peak else f"{'?':>9} {'':>9} {'':>7}"
            time_s = f"{_fmt_time(longest[2]):>11} {longest[3]['time']:>11} {_fmt_time(max(longest[2] * args.time_factor, args.min_time * 60)):>11}" if longest else f"{'?':>11} {'':>11} {'':>11}"
            names = " / ".join(dict.fromkeys(d[0].removeprefix(f"{dataset}/") for d in (peak, longest) if d))
            print(f"{dataset:<10} {cls:<15} {len(done):>4} {g['open']:>4}  {mem_s}   {time_s}  {names}")
        for key, st, limit in g["limit"]:
            print(f"{'':<10} {'':<15} !! {key.removeprefix(f'{dataset}/')}: {st} at {limit} - "
                  + (f"this class needs more than {limit}" if st in ("OUT_OF_MEMORY", "TIMEOUT") else "retried (lower bound for the estimate)"))
    print("\nSet these per dataset in [resources.<class>] of the full experiment's TOML. The pilot covers only its grid points "
          "(largest RP models); solve times vary more across demand levels / TMs than memory - keep a margin on time.")


def cmd_prioritize(args) -> None:
    rdir, state = load_state(args.run)
    if args.nice_step is not None:
        state["nice_step"] = _nice_step(args.nice_step)  # also used by later restarts
    status = classify(state, Slurm.query({current_job(t) for t in state["tasks"].values() if current_job(t)}))
    prioritize(state, [k for k in state["tasks"] if k != "evaluate" and status[k][0] == PENDING], Slurm(dry_run=args.dry_run))
    if args.nice_step is not None and not args.dry_run:
        save_state(rdir, state)


def cmd_log(args) -> None:
    _, state = load_state(args.run)
    matches = [k for k in state["tasks"] if fnmatch.fnmatch(k, args.key)]
    if len(matches) != 1:
        sys.exit(f"'{args.key}' matches {len(matches)} tasks" + (f": {matches[:10]}" if matches else ""))
    task = state["tasks"][matches[0]]
    for attempt in task["attempts"]:
        print(f"attempt job {attempt['job']} ({attempt['time']}, {attempt['res']}): {attempt['log']}")
    log = Path(task["attempts"][-1]["log"])
    if log.exists():
        print(f"\n--- last {args.lines} lines of {log} ---")
        print("\n".join(log.read_text(errors="replace").splitlines()[-args.lines:]))
    else:
        print("(log does not exist yet)")


########################################################################################################################
# Task pool: workers that pack tasks onto a machine (pool.py) - `worker`, `local`, and the pool mode of status/restart/resources
########################################################################################################################

DEFAULT_IDLE_HOURS = 3.0


def _load_config(name_or_config: str) -> tuple[Path, dict]:
    """(TOML path, config) from a TOML file, or a run name resolved to experiments/<name>.toml."""
    path = Path(name_or_config)
    if not path.is_file():
        path = HERE / "experiments" / f"{name_or_config}.toml"
    if not path.is_file():
        sys.exit(f"No config '{name_or_config}' (give a TOML file or the name of one in {HERE / 'experiments'})")
    return path.resolve(), tomllib.loads(path.read_text())


def estimate_levels(key: str) -> list[str]:
    """Estimate levels of a task, most specific first: the task itself, then the same task / edge with the same RP count,
    the same task / edge, and the resource class - all within its dataset (demand level and TM are ignored)."""
    parts = key.split("/")
    if parts[-1] in ("prepare", "truth-original") and len(parts) >= 2:
        return [key, f"{parts[0]}/{parts[-1]}"]
    if len(parts) != 6:  # evaluate (or an unknown key format): only its own measurements
        return [key]
    dataset, clusters, task, edge = parts[0], parts[2], parts[-2], parts[-1]
    return [key, f"{dataset}/{task}/{edge}/{clusters}", f"{dataset}/{task}/{edge}", f"{dataset}/class:{resource_class(key)}"]


def pool_specs(plan: dict, keys: list[str]) -> dict:
    """pool.Worker specs of the given tasks (plan order = dependency order); `python` becomes this interpreter."""
    specs = {}
    for key in keys:
        task = plan[key]
        cmd = task["cmd"].split(" ")
        specs[key] = {"cmd": [sys.executable, *cmd[1:]] if cmd[0] == "python" else cmd, "deps": task["deps"], "cpus": task["res"]["cpus"],
                      "prior_mem_mb": _mem_mb(task["res"]["mem"].upper().removesuffix("B")), "prior_time_s": _elapsed_s(task["res"]["time"]) or 0,
                      "rank": task.get("rank", 0), "dataset_rank": task.get("dataset_rank", 0), "low": task.get("low", False),
                      "after_all": key == "evaluate"}  # evaluate: after all others (like afterany)
    return specs


def select_keys(plan: dict, patterns: list[str], with_deps: bool = False) -> list[str]:
    selected = {k for k in plan if any(fnmatch.fnmatch(k, p) for p in patterns)}
    if not selected:
        sys.exit(f"No task matches {patterns} (task keys look like 'TX-123BT/sd1/prepare', see README)")
    if with_deps:
        stack = list(selected)
        while stack:
            for dep in plan[stack.pop()]["deps"]:
                if dep not in selected:
                    selected.add(dep)
                    stack.append(dep)
    return [k for k in plan if k in selected]


def seed_records(cfg: dict) -> list[dict]:
    """Measurements of this run and of [pool] seed_runs: runs/<run>/measurements.json (Slurm runs, `resources --save`)
    and runs/<run>/pool/results/ (pool runs)."""
    records = []
    for run in dict.fromkeys([cfg["name"], *cfg.get("pool", {}).get("seed_runs", [])]):
        rdir = RUNS_DIR / run
        if (rdir / "measurements.json").exists():
            records += [{**r, "source": f"slurm:{run}"} for r in json.loads((rdir / "measurements.json").read_text())]
        if (rdir / "pool" / "results").is_dir() and run != cfg["name"]:  # the own pool is read by the worker itself
            records += [{**r, "source": f"pool:{run}"} for r in pool.Store(rdir / "pool").results()]
    return records


def _slurm_end_time() -> float | None:
    """End of the current Slurm job (start + time limit) as a timestamp, if running inside one."""
    job = os.environ.get("SLURM_JOB_ID")
    if not job:
        return None
    out = subprocess.run(["squeue", "-h", "-j", job, "-o", "%e"], capture_output=True, text=True).stdout.strip()
    try:
        return datetime.datetime.fromisoformat(out).timestamp()
    except ValueError:
        return None


def make_worker(cfg: dict, specs: dict, store: "pool.Store", *, cores: int, mem_mb: float, **kwargs) -> "pool.Worker":
    pcfg = cfg.get("pool", {})
    estimator = pool.Estimator(specs, estimate_levels, mem_safety=float(pcfg.get("mem_safety", 1.2)),
                               time_safety=float(pcfg.get("time_safety", 1.5)), time_level=lambda level: "/class:" not in level)
    kwargs.setdefault("mem_fraction", float(pcfg.get("mem_fraction", 0.9)))
    kwargs.setdefault("disk_min_free_mb", float(pcfg.get("disk_min_free_gb", DEFAULT_DISK_MIN_FREE_GB)) * 1024)
    if pcfg.get("rank_offset_hours") is not None:  # soft dataset order; absent = strict (grid.datasets order first)
        kwargs.setdefault("rank_offset_s", float(pcfg["rank_offset_hours"]) * 3600)
    return pool.Worker(specs, store, estimator, cwd=HERE.parent.parent, cores=cores, mem_mb=mem_mb, seed_records=seed_records(cfg), **kwargs)


def _parse_mem_arg(value: str | None, name: str) -> float | None:
    if value is None:
        return None
    mb = _mem_mb(value.upper().removesuffix("B"))
    if mb is None:
        sys.exit(f"{name} '{value}': use e.g. 700G or 16000M")
    return mb


def cmd_worker(args) -> None:
    """Run the shared pool of a config on this machine (a Slurm node or any other machine with access to the repo)."""
    config_path, cfg = _load_config(args.config)
    plan = build_plan(cfg)
    keys = select_keys(plan, args.patterns or ["*"])
    rdir = RUNS_DIR / cfg["name"]
    if (rdir / "state.json").exists():
        sys.exit(f"'{rdir}' holds a per-task Slurm run (state.json) - use a different run name for the pool")
    store = pool.Store(rdir / "pool")
    meta = store.root / "meta.json"
    if not meta.exists():
        pool._write_json_atomic(meta, {"config": str(config_path), "created": _now()})
    total, _ = pool.machine_memory_mb()
    mem_mb = _parse_mem_arg(args.mem, "--mem") or total
    if mem_mb is None:
        sys.exit("Cannot determine this machine's memory - pass --mem")
    end_time = time.time() + args.hours * 3600 if args.hours else _slurm_end_time()
    idle_h = args.idle_hours if args.idle_hours is not None else float(cfg.get("pool", {}).get("idle_hours", DEFAULT_IDLE_HOURS))
    chain = None
    if args.chain_script:
        def chain():
            job = _sbatch_from_job(args.chain_script)
            if job:
                store.add_job(job, {"submitted_by": os.environ.get("SLURM_JOB_ID") or "local", "script": args.chain_script})
            return job
    worker = make_worker(cfg, pool_specs(plan, keys), store, cores=args.cores or os.cpu_count() or 1, mem_mb=mem_mb,
                         end_time=end_time, idle_s=idle_h * 3600, max_tasks=args.max_tasks, node_base=args.node_dir,
                         chain_after_s=args.chain_after_hours * 3600 if args.chain_script else None, chain=chain)
    sys.exit(worker.run())


def _sbatch_from_job(script: str) -> str | None:
    """sbatch a script from inside a job: without the job's SLURM_*/SBATCH_* variables, which would otherwise leak into
    the new job's options or environment. Returns the job id, or None (the error is printed)."""
    env = {k: v for k, v in os.environ.items() if not k.startswith(("SLURM_", "SBATCH_", "SRUN_"))}
    out = subprocess.run(["sbatch", "--parsable", script], capture_output=True, text=True, env=env)
    if out.returncode != 0:
        print(f"{_now()} sbatch failed: {(out.stderr or out.stdout).strip()}", flush=True)
        return None
    return out.stdout.strip().split(";")[0]


def _pool_settings(cfg: dict) -> dict:
    """[pool] settings for whole-node workers (submit-workers); cores and mem are required there."""
    p = cfg.get("pool", {})
    missing = [k for k in ("cores", "mem") if k not in p]
    if missing:
        sys.exit(f"[pool] needs {missing} for submit-workers (MUSICA zen4_0768: cores = 192, mem = \"700G\")")
    walltime = str(p.get("walltime", "3-00:00:00"))
    chain_h = float(p.get("chain_after_hours", 24))
    if chain_h * 3600 >= (_elapsed_s(walltime) or 0):
        sys.exit(f"[pool] chain_after_hours ({chain_h:g}) must be shorter than walltime ({walltime})")
    mem_mb = _mem_mb(str(p["mem"]).upper().removesuffix("B"))
    if mem_mb is None:
        sys.exit(f"[pool] mem '{p['mem']}': use e.g. \"700G\"")
    return {"cores": int(p["cores"]), "mem": str(p["mem"]), "mem_mb": mem_mb, "walltime": walltime, "chain_hours": chain_h,
            "workers": int(p.get("workers", 3)), "mem_fraction": float(p.get("mem_fraction", 0.9))}


def work_estimate(cfg: dict, plan: dict, store: "pool.Store", settings: dict) -> None:
    """Print the estimated remaining work in node-hours (memory- and core-bound) and the critical path."""
    specs = pool_specs(plan, list(plan))
    estimator = make_worker(cfg, specs, store, cores=settings["cores"], mem_mb=settings["mem_mb"]).est
    for record in store.results():
        estimator.add(record)
    snap = store.snapshot(specs)
    open_keys = [k for k in plan if snap[k][0] not in (pool.DONE, pool.FAILED)]
    if not open_keys:
        print("No open tasks.")
        return
    est = {k: estimator.estimate(k) for k in plan}
    mem_h = sum(est[k]["mem_mb"] * est[k]["time_s"] for k in open_keys) / (settings["mem_fraction"] * settings["mem_mb"]) / 3600
    core_h = sum(min(specs[k]["cpus"], settings["cores"]) * est[k]["time_s"] for k in open_keys) / settings["cores"] / 3600
    measured_mem = sum(est[k]["mem_src"] != "prior" for k in open_keys)
    measured_time = sum(est[k]["time_src"] != "prior" for k in open_keys)
    critical, kids = {}, {}
    for key, task in plan.items():
        for dep in task["deps"]:
            kids.setdefault(dep, []).append(key)
    for key in reversed(list(plan)):
        critical[key] = (est[key]["time_s"] if key in open_keys else 0) + max((critical[c] for c in kids.get(key, [])), default=0)
    node_h = max(mem_h, core_h)
    print(f"Open tasks: {len(open_keys)} of {len(plan)}; estimates measured for memory {measured_mem}, runtime {measured_time} "
          f"(the rest uses the TOML [resources.*] - their 'time' is a limit, not a runtime, so this is an upper bound)")
    print(f"Estimated work: {node_h:,.0f} node-hours ({'memory' if mem_h >= core_h else 'cores'}-bound; memory {mem_h:,.0f}, "
          f"cores {core_h:,.0f}) on nodes with {settings['cores']} cores / {settings['mem']} x {settings['mem_fraction']:g}")
    print(f"Longest dependency chain: {max(critical.values()) / 3600:,.1f} h (no number of nodes finishes faster)")
    for n in (1, 2, 3, 5, 10):
        print(f"  {n:>2} worker chain(s): ~{max(node_h / n, max(critical.values()) / 3600) / 24:,.1f} days")


def cmd_submit_workers(args) -> None:
    """Submit whole-node worker jobs for the task pool of a config; each chains its own successor."""
    config_path, cfg = _load_config(args.config)
    plan = build_plan(cfg)
    settings = _pool_settings(cfg)
    rdir = RUNS_DIR / cfg["name"]
    if (rdir / "state.json").exists():
        sys.exit(f"'{rdir}' holds a per-task Slurm run (state.json) - use a different run name for the pool")
    pool_root = rdir / "pool"
    # A dry run must not create the pool: estimate from an empty temporary store instead
    store = pool.Store(Path(tempfile.mkdtemp(prefix="mk-dry-pool-")) if args.dry_run and not pool_root.exists() else pool_root)
    if not (pool_root / "meta.json").exists() and not args.dry_run:
        pool._write_json_atomic(pool_root / "meta.json", {"config": str(config_path), "created": _now()})
    work_estimate(cfg, plan, store, settings)
    if args.estimate_only:
        return

    slurm_cfg = cfg["slurm"]
    mail_user = slurm_cfg.get("mail_user") or os.environ.get("MK_MAIL_USER", "")
    # Few long jobs: [pool] mail_type (e.g. BEGIN,END,FAIL) may differ from the per-task [slurm] mail_type
    mail_type = cfg.get("pool", {}).get("mail_type", slurm_cfg.get("mail_type", "FAIL"))
    mail = f"#SBATCH --mail-type={mail_type}\n#SBATCH --mail-user={mail_user}\n" if mail_user else ""
    if not mail_user:
        print("note: no mail address ([slurm] mail_user or $MK_MAIL_USER) - the worker jobs send no mails")
    script = pool_root / "worker.sbatch"
    text = WORKER_SBATCH_TEMPLATE.format(account=slurm_cfg["account"], partition=slurm_cfg["partition"], qos=slurm_cfg.get("qos", slurm_cfg["partition"]),
                                         walltime=settings["walltime"], jobname=f"wrk-{cfg['name']}", jobs_dir=pool_root / "jobs", mail=mail,
                                         name=cfg["name"], chain_hours=settings["chain_hours"], setup=slurm_cfg.get("setup", "").strip(),
                                         repo=slurm_cfg["repo"], config=config_path, cores=settings["cores"], mem=settings["mem"], script=script)
    if args.dry_run:
        print(f"\n--- {script} (dry run: not written) ---\n{text}")
    else:
        script.write_text(text, newline="\n")
    n = args.workers or settings["workers"]
    print(f"\nSubmitting {n} worker chain(s): {settings['walltime']} whole-node jobs, each submitting its successor after "
          f"{settings['chain_hours']:g} h while tasks remain" + ("  (dry run)" if args.dry_run else ""))
    slurm = Slurm(dry_run=args.dry_run)
    for _ in range(n):
        job = slurm.sbatch([str(script)])
        if not args.dry_run:
            store.add_job(job, {"submitted_by": "submit-workers", "script": str(script)})
    print(f"Logs: {pool_root / 'jobs'}/worker_<job>.out; status: cluster.py status {cfg['name']}")


def cmd_local(args) -> None:
    """Run tasks of a config on this machine in dependency order (up to --jobs at once) in a throw-away pool."""
    if args.jobs < 1:
        sys.exit("--jobs must be >= 1")
    _, cfg = _load_config(args.config)
    plan = build_plan(cfg)
    keys = select_keys(plan, args.patterns, args.with_deps)
    cores = os.cpu_count() or 1
    thread_cap = args.threads or max(1, cores // args.jobs)  # parallel slots share the machine's cores
    log_dir = Path(args.log_dir) if args.log_dir else (RUNS_DIR / f"{cfg['name']}-local" / "logs" if args.jobs > 1 else None)
    specs = pool_specs(plan, keys)

    print(f"{len(keys)} task(s) to run locally" + (f", up to {args.jobs} at once" if args.jobs > 1 else "")
          + (f", logs in {log_dir}" if log_dir else "") + ("  (dry run)" if args.dry_run else ""))
    if args.dry_run:
        for i, key in enumerate(keys, 1):
            cmd = [a.replace("@THREADS@", str(min(specs[key]["cpus"], thread_cap, cores))).replace("@NODEDIR@", "<node-dir>") for a in specs[key]["cmd"]]
            print(f"[{i}/{len(keys)}] {key}\n    " + " ".join(cmd))
        return

    total, _ = pool.machine_memory_mb()
    with tempfile.TemporaryDirectory(prefix="mk-local-pool-") as tmp:
        store = pool.Store(Path(tmp), log_dir=log_dir)
        # Memory packing off: -j is the concurrency (the TOML memory is sized for Slurm jobs, not this machine); the
        # memory guard still evicts the newest task if the machine runs out of memory
        worker = make_worker(cfg, specs, store, cores=cores, mem_mb=total or 16 * 1024, mem_packing=False, idle_s=0,
                             max_tasks=args.jobs, thread_cap=thread_cap, keep_going=args.keep_going,
                             console=args.jobs == 1 and log_dir is None, poll_s=2)
        worker.run()
        snap = store.snapshot(specs)
    done = [k for k in keys if snap[k][0] == pool.DONE]
    failed = [k for k in keys if snap[k][0] == pool.FAILED]
    print(f"\n{len(done)} done, {len(failed)} failed, {len(keys) - len(done) - len(failed)} not run")
    for key in failed:
        log = snap[key][2].get("log")
        print(f"  FAILED {key}" + (f"  (log: {log})" if log else ""))
    if failed:
        sys.exit(1)


def load_pool(run: str) -> tuple[Path, "pool.Store", dict, dict] | None:
    """(run dir, store, config, plan) of a pool run, or None if the run is not a pool run."""
    rdir = run_dir(run)
    meta = rdir / "pool" / "meta.json"
    if (rdir / "state.json").exists() or not meta.exists():
        return None
    config = json.loads(meta.read_text())["config"]
    _, cfg = _load_config(config)
    return rdir, pool.Store(rdir / "pool"), cfg, build_plan(cfg)


def pool_status(plan: dict, store: "pool.Store") -> dict:
    """{key: (category, info)} with the categories of `status` (blocked = waits for a failed task)."""
    snap = store.snapshot(plan)
    status = {}
    for key, task in plan.items():  # plan order: parents first
        state, attempt, info = snap[key]
        if state == pool.DONE:
            cat = DONE
        elif state == pool.FAILED:
            cat = FAILED
        elif any(status[d][0] in (FAILED, BLOCKED) for d in task["deps"]):
            cat = BLOCKED
        elif state == pool.RUNNING:
            cat = RUNNING
        else:
            cat = PENDING
        status[key] = (cat, {**info, "attempt": attempt, "state": state})
    return status


def _kind(key: str) -> str:
    return "/".join(key.split("/")[-2:]) if "/c" in key else key.split("/")[-1]  # e.g. 'regret/Markov', 'prepare'


def _print_counts(status: dict) -> None:
    counts = {}
    for key, (cat, _) in status.items():
        counts.setdefault(_kind(key), dict.fromkeys(CATEGORIES, 0))[cat] += 1
    width = max(len(k) for k in counts)
    print(f"{'task':<{width}}  {'total':>6}" + "".join(f"  {c:>8}" for c in CATEGORIES))
    for k, row in counts.items():
        print(f"{k:<{width}}  {sum(row.values()):>6}" + "".join(f"  {row[c] or '':>8}" for c in CATEGORIES))
    totals = {c: sum(r[c] for r in counts.values()) for c in CATEGORIES}
    print(f"{'TOTAL':<{width}}  {len(status):>6}" + "".join(f"  {totals[c]:>8}" for c in CATEGORIES))


def cmd_pool_status(args, rdir: Path, store: "pool.Store", plan: dict) -> None:
    status = pool_status(plan, store)
    _print_counts(status)
    now = time.time()
    workers = store.workers()
    print(f"\nWORKERS ({len(workers)})")
    for wid, w in sorted(workers.items(), key=lambda x: x[1].get("started", "")):
        alive = not w.get("exited") and now - w.get("beat", 0) < pool.STALE_S
        state = "active" if alive else ("exited " + w["exited"] if w.get("exited") else "lost (no heartbeat)")
        size = f"{w['cores']} cores, {w['mem_mb'] / 1024:.0f} GB, started {w.get('started')}" if w.get("cores") else ""
        print(f"  {wid:<40} {state:<28} {len(w.get('running', [])):>3} running  {size}")
    jobs = store.jobs()
    if jobs and shutil.which("squeue"):  # queued / running worker jobs (chained successors included)
        out = subprocess.run(["squeue", "-h", "-j", ",".join(sorted(jobs)), "-o", "%i|%T|%r|%S"], capture_output=True, text=True).stdout
        active = [line.split("|") for line in out.splitlines() if line.count("|") == 3]
        print(f"\nWORKER JOBS: {len(jobs)} submitted, {sum(a[1] == 'RUNNING' for a in active)} running, "
              f"{sum(a[1] == 'PENDING' for a in active)} queued")
        for job, st, reason, start in active:
            print(f"  {job:<12} {st:<10} {reason if st == 'PENDING' else '':<20} {'expected start ' + start if st == 'PENDING' and start != 'N/A' else ''}")
    retries = [r for r in store.results() if r["outcome"] in (pool.EVICTED, pool.INTERRUPTED)]
    if retries:
        print(f"\nRETRIED ATTEMPTS: {sum(r['outcome'] == pool.EVICTED for r in retries)} evicted (memory), "
              f"{sum(r['outcome'] == pool.INTERRUPTED for r in retries)} interrupted (walltime / worker stopped)")
    shown = [args.list] if args.list else [FAILED, BLOCKED]
    for cat in shown:
        keys = [k for k, (c, _) in status.items() if c == cat and (args.filter is None or fnmatch.fnmatch(k, args.filter))]
        if not keys:
            continue
        print(f"\n{cat.upper()} ({len(keys)})")
        if cat == BLOCKED and not args.list:
            roots = {}
            for k in keys:
                stack, seen = list(plan[k]["deps"]), set()
                while stack:
                    d = stack.pop()
                    if d in seen:
                        continue
                    seen.add(d)
                    if status[d][0] == FAILED:
                        roots.setdefault(d, []).append(k)
                    elif status[d][0] == BLOCKED:
                        stack.extend(plan[d]["deps"])
            for root, ks in roots.items():
                print(f"  {len(ks):>4} task(s) waiting for {root}")
            continue
        for k in keys:
            info = status[k][1]
            peak = f"peak {info['peak_rss_mb'] / 1024:.1f} GB" if info.get("peak_rss_mb") else ""
            elapsed = str(datetime.timedelta(seconds=int(info["elapsed_s"]))) if info.get("elapsed_s") is not None else ""
            extra = f"exit {info.get('rc')}" if cat == FAILED else (f"on {info.get('worker')}" if cat == RUNNING else "")
            print(f"  {k:<55} attempt {info['attempt']:<3} {elapsed:>9} {peak:<16} {extra}"
                  + (f"\n      log: {info['log']}" if info.get("log") else ""))
    if not args.list:
        print("\nRetry failed tasks (and unblock the tasks waiting for them): cluster.py restart <run> --failed")


def cmd_pool_restart(args, store: "pool.Store", plan: dict) -> None:
    if args.mem or args.mem_factor or args.cpus or args.time or args.include_pending:
        print("note: --mem/--mem-factor/--cpus/--time/--include-pending do not apply to pool runs (estimates are automatic)")
    status = pool_status(plan, store)
    selected = [k for k, (cat, _) in status.items() if cat == FAILED and (args.failed or any(fnmatch.fnmatch(k, p) for p in args.patterns))]
    if not selected:
        sys.exit("Nothing to restart (only failed tasks can be retried; running workers pick them up again)")
    print(f"Retrying {len(selected)} failed task(s)" + ("  (dry run)" if args.dry_run else ""))
    for key in selected:
        print(f"  {key}")
        if not args.dry_run:
            store.reset(key, status[key][1]["attempt"])


def cmd_cancel(args) -> None:
    pool_run = load_pool(args.run)
    if pool_run:  # all worker jobs incl. queued successors; running tasks are retried by later workers
        jobs = sorted(pool_run[1].jobs())
        print(f"Cancelling {len(jobs)} worker job(s) (finished ones are ignored by scancel)")
        Slurm().scancel(jobs)
        return
    _, state = load_state(args.run)
    jobs = sorted({g["job"] for g in state["groups"].values()} |
                  {a["job"] for t in state["tasks"].values() for a in t["attempts"] if "_" not in a["job"]})
    print(f"Cancelling {len(jobs)} job(s) / array(s)")
    Slurm().scancel(jobs)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("submit", help="Submit all tasks of a config as job arrays with dependencies")
    p.add_argument("config", help="TOML experiment file, e.g. research/MK/experiments/experiment.toml")
    p.add_argument("--dry-run", action="store_true", help="Print the sbatch calls and write the files to runs/<name>-dryrun/ without submitting")
    p.set_defaults(func=cmd_submit)
    p = sub.add_parser("status", help="Task counts per kind and state; lists failed / blocked tasks")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("--list", choices=CATEGORIES, help="List all tasks in this state instead")
    p.add_argument("--filter", help="Only list tasks matching this glob pattern, e.g. 'TX-123BT/*'")
    p.set_defaults(func=cmd_status)
    p = sub.add_parser("restart", help="Resubmit failed tasks (and everything waiting for them)")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("patterns", nargs="*", default=[], help="Glob patterns of task keys, e.g. 'TX-123BT/sd0.5/c21/base/main/Truth' or 'TX-123BT/*/regret/*'")
    p.add_argument("--failed", action="store_true", help="Select all failed tasks")
    p.add_argument("--include-pending", action="store_true", help="Also resubmit matching tasks that are still queued (e.g. to change their resources)")
    p.add_argument("--mem", help="New memory for the selected tasks, e.g. 200G")
    p.add_argument("--mem-factor", type=float, help="Scale the memory of the selected tasks, e.g. 1.5")
    p.add_argument("--cpus", type=int, help="New core count for the selected tasks")
    p.add_argument("--time", help="New time limit for the selected tasks, e.g. 3-00:00:00")
    p.add_argument("--dry-run", action="store_true", help="Print what would be cancelled / submitted")
    p.set_defaults(func=cmd_restart)
    p = sub.add_parser("prioritize", help="Re-apply the nice (rank x nice_step) of the queued jobs, e.g. with a new --nice-step")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("--nice-step", type=int, help="New nice per rank, stored for later restarts (default: the run's nice_step)")
    p.add_argument("--dry-run", action="store_true", help="Print the scontrol calls only")
    p.set_defaults(func=cmd_prioritize)
    p = sub.add_parser("resources", help="Peak memory / runtime per dataset and resource class, with suggested [resources.*] values")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("--mem-factor", type=float, default=1.3, help="Suggested mem = factor x max peak (default 1.3)")
    p.add_argument("--time-factor", type=float, default=2.0, help="Suggested time = factor x max elapsed (default 2.0)")
    p.add_argument("--min-time", type=int, default=30, help="Minimum suggested time in minutes (default 30)")
    p.add_argument("--save", action="store_true", help="Slurm runs: also write runs/<run>/measurements.json (seed for pool runs)")
    p.set_defaults(func=cmd_resources)
    p = sub.add_parser("log", help="Attempts and log tail of one task")
    p.add_argument("run", help="Run name or its TOML file")
    p.add_argument("key", help="Task key (glob allowed if it matches exactly one task)")
    p.add_argument("-n", "--lines", type=int, default=40)
    p.set_defaults(func=cmd_log)
    p = sub.add_parser("local", help="Run tasks on this machine without Slurm (sequentially, in dependency order)")
    p.add_argument("config", help="TOML experiment file or its name, e.g. pilot")
    p.add_argument("patterns", nargs="+", help="Glob patterns of task keys, e.g. 'TX-123BT/sd1/prepare' or '*/prepare'")
    p.add_argument("--with-deps", action="store_true", help="Also run the tasks the selected ones depend on (finished ones are skipped by --no-overwrite)")
    p.add_argument("-j", "--jobs", type=int, default=1, help="Run up to N tasks at once, each as soon as its dependencies have finished (default 1)")
    p.add_argument("--threads", type=int, help="Gurobi threads per task (default: the task's cpus, at most CPU count / jobs)")
    p.add_argument("--keep-going", action="store_true", help="Continue after a failure (tasks depending on it are skipped)")
    p.add_argument("--log-dir", help="Write each task's output to <log-dir>/<key>.<attempt>.log instead of the console "
                                     "(with --jobs > 1 always, default runs/<name>-local/logs/)")
    p.add_argument("--dry-run", action="store_true", help="Print the commands only")
    p.set_defaults(func=cmd_local)
    p = sub.add_parser("worker", help="Run the shared task pool of a config on this machine (packs tasks by memory estimate and cores)")
    p.add_argument("config", help="TOML experiment file or its name, e.g. experiment")
    p.add_argument("patterns", nargs="*", help="Only these tasks (glob patterns; default: all). Dependencies outside the selection count as done")
    p.add_argument("--cores", type=int, help="Cores to use (default: all CPUs of this machine)")
    p.add_argument("--mem", help="Memory to use, e.g. 700G (default: this machine's RAM); [pool] mem_fraction of it is packed")
    p.add_argument("--hours", type=float, help="Walltime of this worker (default: the Slurm job's end, else unlimited)")
    p.add_argument("--idle-hours", type=float, help=f"Exit after this long without anything to run (default: [pool] idle_hours or {DEFAULT_IDLE_HOURS:g})")
    p.add_argument("--max-tasks", type=int, help="At most this many tasks at once")
    p.add_argument("--node-dir", help="Base directory for Gurobi node files (default: $TMPDIR, else the system temp dir)")
    p.add_argument("--chain-script", help="sbatch this script once --chain-after-hours have passed, if tasks remain (set by submit-workers)")
    p.add_argument("--chain-after-hours", type=float, default=24, help="When to submit the successor (default 24)")
    p.set_defaults(func=cmd_worker)
    p = sub.add_parser("submit-workers", help="Submit whole-node worker jobs for the task pool; each submits its successor after [pool] chain_after_hours")
    p.add_argument("config", help="TOML experiment file or its name, e.g. experiment")
    p.add_argument("--workers", type=int, help="Number of worker chains (default: [pool] workers or 3); can be repeated later to add more")
    p.add_argument("--estimate-only", action="store_true", help="Only print the estimated remaining work")
    p.add_argument("--dry-run", action="store_true", help="Print the job script and sbatch calls without submitting")
    p.set_defaults(func=cmd_submit_workers)
    p = sub.add_parser("cancel", help="Cancel all jobs of a run")
    p.add_argument("run", help="Run name or its TOML file")
    p.set_defaults(func=cmd_cancel)
    args = parser.parse_args()
    if args.command == "restart" and not (args.failed or args.patterns):
        parser.error("restart needs --failed and/or task patterns")
    args.func(args)


if __name__ == "__main__":
    main()
