name: CI

on:
  push:
  pull_request:

jobs:
  run_tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        isMainBranch:
          - ${{ contains(github.ref, 'main') }}  # Check if the branch is main
        exclude:
          - isMainBranch: false
            os: windows-latest  # Exclude Windows for non-main branches
          - isMainBranch: false
            os: macos-latest  # Exclude macOS for non-main branches
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: 'recursive'

      - name: Install MPI
        uses: mpi4py/setup-mpi@v1.3.2
        with:
          mpi: 'openmpi'

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3.2.0
        env:
          CC: mpicXX
        with:
          environment-file: environment.yml
          activate-environment: LEGO-Pyomo_env

      - name: Run tests
        run: python -m pytest tests/